### ISSUE TITLE
安装包版本号

### ISSUE THREAD

**Issue by Yao-DY** [niuhuan/pikapika#100]
首先感谢开发者的无私分享，比原版要更符合现在流行的界面，好看了不少。
但一直以来有个小问题，安卓版在安装的时候显示出来的版本号一直是1.0.0，版本ID一直是1，能不能把这两个更改为Release里响应的值呢

**Comment by niuhuan** [comment]
请在关于里面查看版本号。

**Comment by niuhuan** [comment]
主要还是为了能前后覆盖安装。

**Comment by Yao-DY** [comment]
> 主要还是为了能前后覆盖安装。

明白了

**Comment by wwmbao** [comment]
安装新版后，会有个新的app图标，打开这个新安装的app后，旧的所有数据都没有，账号信息也没有，这个怎么解决？

**Comment by Yao-DY** [comment]
> 安装新版后，会有个新的app图标，打开这个新安装的app后，旧的所有数据都没有，账号信息也没有，这个怎么解决？

你是之前装的1.1.10（或者更早的），最近装了1.2.1（或者更新的）的么，那你可能需要迁移一下数据，参考[这篇文档](https://github.com/niuhuan/pikapika/issues/56)。如果不是我所说的这个情况的话，那我就不知道了，等开发者解答吧

**Comment by niuhuan** [comment]
> 安装新版后，会有个新的app图标，打开这个新安装的app后，旧的所有数据都没有，账号信息也没有，这个怎么解决？

你可以先用旧的账号登录APP, 都迁移出来之后移动文件夹, 然后关闭APP, 把旧的数据移动/覆盖新的版本, 然后重新打开APP, 新的版本会兼容旧的版本。

**Comment by Tsherlock01** [comment]
nice

**Comment by XQBZJC** [comment]
下载源码后咋安装嘞？安卓的

**Comment by niuhuan** [comment]
通过Releases下载安装，安卓设备要选择和您设备一样的abi，您也可以参考github的官网文档了解如何使用Releases。
