### ISSUE TITLE
文件名太长了不能导出

### ISSUE THREAD

**Issue by YangHgRi** [niuhuan/pikapika#101]
出现异常后手动设定文件夹名怎么样
![Screenshot_20220224_161111](https://user-images.githubusercontent.com/57426791/155485105-f9962c27-5f6f-4748-a9ae-7e5f32ada401.jpg)

**Comment by niuhuan** [comment]
我的天啊... 😨

**Comment by niuhuan** [comment]
最新的release, 设置最下面
