### ISSUE TITLE
无法登入

### ISSUE THREAD

**Issue by EvatsugDnalloR** [niuhuan/pikapika#102]
更新到1.4.0后要求重新登录，然后输入账号密码后，一直显示无法登入，具体为
登录失败
请检查账号密码
PlatformException（Post
＂https://picaapi.picacomic.com
/auth/sign-in＂:x509:certificate
signed by unknown authority，null）
用官方版确认了一遍帐号密码是正确的，可以登入
并且尝试回退到1.3.9以后还是无法登入

**Comment by EvatsugDnalloR** [comment]
如果需要的话我去抓个log，虽然不是很精通...

**Comment by EvatsugDnalloR** [comment]
使用的是安卓amr64版本

**Comment by niuhuan** [comment]
> 使用的是安卓amr64版本

我可以确认是网络问题, 并不是账号密码的原因.

 x509:certificate signed by unknown authority, 这是说证书不可信, 未知的作者, 您可以先更换您的分流或者代理尝试一下。

**Comment by EvatsugDnalloR** [comment]
> > 使用的是安卓amr64版本
> 
> 我可以确认是网络问题, 并不是账号密码的原因.
> 
>  x509:certificate signed by unknown authority, 这是说证书不可信, 未知的作者, 您可以先更换您的分流或者代理尝试一下。
> 
> 我这里的话刚才试了一下分流3是可以用的, 跟您的地理位置有关系。

不好意思突然想起来adguard给它开了https过滤，我估计它不接受adguard的证书，关了就没问题了...
谢谢，解决了...

**Comment by niuhuan** [comment]
> adguard

暂时不会恰饭, 如果对软件有改进意见可以提新的issues。
