### ISSUE TITLE
滚动条不能隐藏，好像

### ISSUE THREAD

**Issue by RichardZhang4** [niuhuan/pikapika#103]

**Comment by niuhuan** [comment]
你是说下面那个条条吗？

**Comment by niuhuan** [comment]
什么系统下, 哪个滚动条? 简单讲一下

**Comment by RichardZhang4** [comment]
> 什么系统下, 哪个滚动条? 简单讲一下

三星，看图时的那个标题栏和进度条
![Uploading Screenshot_20220311-214047.jpg…]()

**Comment by niuhuan** [comment]
你图片没传完, 能隐藏的, 左下角那个框框, 或者点菜单, 设置一下单击全屏什么的

**Comment by RichardZhang4** [comment]
好的，谢谢
