### ISSUE TITLE
【建议】评论区点赞按钮变大

### ISSUE THREAD

**Issue by ghost** [niuhuan/pikapika#104]
评论右边那个❤太小了 几乎点不上 能大点吗 辛苦作者大大了

**Comment by niuhuan** [comment]
确实太小了，如果放在下面又会因为一个按钮让卡片变高，觉得不好看。

![Screenshot_20220313-001801](https://user-images.githubusercontent.com/20847533/158025960-f4480b05-6dbe-44a6-b81a-65ba73f46626.png)

![Screenshot_20220313-001801](https://user-images.githubusercontent.com/20847533/158025974-2d0ed002-3a1d-452e-80f0-ade71346c7fd.png)

**Comment by 850710247liu** [comment]
像b站那样 把等级放到人物昵称旁边 点赞自成一行 感觉如何

**Comment by niuhuan** [comment]
最后一个心自己占一行不好看, 而且感觉浪费了很多空间, 😮‍💨

**Comment by 850710247liu** [comment]
> 最后一个心自己占一行不好看, 而且感觉浪费了很多空间, 😮‍💨   

把心变大 让它多占一行评论 如何 (⊙o⊙)
