### ISSUE TITLE
切换页数的功能

### ISSUE THREAD

**Issue by ELIZABETH947** [niuhuan/pikapika#105]
能否加一个切换页数的功能呢？我感觉这个功能还是蛮好用的。原版有这个功能，这个没有有点遗憾
![Screenshot_2022_0313_111230](https://user-images.githubusercontent.com/101488561/158043369-f8eba476-e086-418a-ab6e-ec1b17ed9cbd.png)

**Comment by niuhuan** [comment]
分页器模式下点击页数就可以
