### ISSUE TITLE
Want prebuilt ARM Linux AppImage

### ISSUE THREAD

**Issue by 4zuk1** [niuhuan/pikapika#106]
Hi, can you release the AppImage for the ARM and ARM64 architecture as well?

I want to try it on my ARM device, thanks!

**Comment by niuhuan** [comment]
ARMLinux is not officially supported.

You can refer to [flutter-engine-builds](https://github.com/niuhuan/flutter-engine-builds)'s *GithubAction* to compile the flutter engine.

The probability can be release arm target if you successfully build the engine.

Modify the download address of engine in [hover](https://github.com/niuhuan/hover), then run **hover build linux-appimage**.

**Comment by niuhuan** [comment]
If you can succeed on arm Linux, there is hope on *apple silicon*.

#97

**Comment by 4zuk1** [comment]
ok thx I'll try xD

**Comment by 4zuk1** [comment]
Since [tonquer/picacg-qt](https://github.com/tonquer/picacg-qt) worked for me, I will abandon this for now xdd

<img src="https://user-images.githubusercontent.com/96861074/158146599-22bc2f09-3b6b-4917-90dc-fa211b83506e.png" height="700"/>

**Comment by niuhuan** [comment]
载不下来编译工具, gclient没有办法设置代理

**Comment by 4zuk1** [comment]
> 载不下来编译工具, gclient没有办法设置代理

Did u try to set proxy for Git instead? xdd
