### ISSUE TITLE
[需求] 滑动切换"章节"和"评论"栏&纯黑色主题

### ISSUE THREAD

**Issue by tototjc** [niuhuan/pikapika#107]
- 希望移动端支持通过左右滑动切换"章节"和"评论"栏目
- 希望添加纯黑色(A屏黑色)的黑暗模式主题

**Comment by niuhuan** [comment]
纯黑有多黑 比如参考哪个APP?

**Comment by tototjc** [comment]
> 纯黑有多黑 比如参考哪个APP?

可以参考微信的深色模式，或者背景色直接用#000，虽然不符合MD规范，但在OLED屏幕上的确会舒适很多

**Comment by niuhuan** [comment]
我发现微信并不是纯黑色的, 应该给弄个自定义主题的功能, 然后把自己的主题分享出来什么的
