### ISSUE TITLE
批量的releases，让我前来看看

### ISSUE THREAD

**Issue by zzcabc** [niuhuan/pikapika#112]
Windows下的压缩
Compress-Archive 当前路径  压缩路径

      - name: 压缩
        run:  Compress-Archive *  ../../windows.zip

**Comment by niuhuan** [comment]
环境快差不多了，啊哈哈哈啊哈，我打算用msys的zip命令， windows的命令行有点头疼

**Comment by zzcabc** [comment]
我注意到 仅支持Linux系统，然后从其他地方copy来了一个win下的打包命令，但是win下还是用Linux的大多数命令

```
montudor/action-zip@v1
Error: Container action is only supported on Linux
```

**Comment by niuhuan** [comment]
泪，终于弄好了
