### ISSUE TITLE
我IOS安装提示 错误

### ISSUE THREAD

**Issue by 1012744647** [niuhuan/pikapika#113]
APPLICATION IS MISSING THE APPLICATION IDENTIFIER ENTITLEMENT   请问如何解决？

**Comment by niuhuan** [comment]
越狱设备用Sideloadly!, 签名方式选择 Ad-hoc

**Comment by 1012744647** [comment]
我用Taurine越狱的   用FILZA安装失败

**Comment by niuhuan** [comment]
需要一个临时签（ad-hoc），不能直接装

**Comment by niuhuan** [comment]
![截屏2022-03-26 上午7 27 28](https://user-images.githubusercontent.com/20847533/160214264-99970eec-07bb-4dfd-895c-9aab5dd5b545.png)
