### ISSUE TITLE
ios设备上的刷新率问题

### ISSUE THREAD

**Issue by wangqs97** [niuhuan/pikapika#114]
首先感谢作者开发的app，功能方面很满意。
目前使用设备为iPhone 13 Pro，支持最高120Hz的自适应刷新功能，但目前使用这app非常不跟手。
我完全不懂开发相关内容，但大概看了一下下面的issue和pr应该可以关注一下
https://github.com/flutter/flutter/issues/90675
https://github.com/flutter/engine/pull/29797

**Comment by niuhuan** [comment]
按照这篇文档修改了一下配置文件 https://www.jianshu.com/p/3ada8afe1abc
是否生效就不知道了

可以下载这个release试一下
CADisableMinimumFrameDurationOnPhone-nosign.ipa

**Comment by wangqs97** [comment]
> 按照这篇文档修改了一下配置文件 https://www.jianshu.com/p/3ada8afe1abc 是否生效就不知道了
> 
> 可以下载这个release试一下 CADisableMinimumFrameDurationOnPhone-nosign.ipa

我提到的那个issue有说这不是plist的问题，测试了新的release包也没有效果。目前flutter似乎正在添加iOS上高刷的feature，作者有兴趣的话可以关注一下
