### ISSUE TITLE
{建议}希望完善收藏功能。

### ISSUE THREAD

**Issue by hanxin1997** [niuhuan/pikapika#115]
嗯，希望增加目前章节和最新章节，可以设计在分类下面，有提示更新就更好了。
为什么需要这个功能，实际上因为现在很多汉化组都到**更新日漫了。但是原版和这个的追漫功能都是基本没有。

**Comment by niuhuan** [comment]
官方并没有这样的接口, 所以不具备追漫的功能
如果需要的话, 只能在程序启动的时候去循环请求所有漫画。这个在设计难度上和效率上并不划得来。

你如果在使用其他漫画APP的话, 可以发送截图展示一下效果。

**Comment by hanxin1997** [comment]
> 
![IMG_20220328_094444](https://user-images.githubusercontent.com/58620096/160356891-696f25bb-cde4-4b96-bcda-e420fa8218dc.jpg)
可以类似这样显示还有多少未读。感觉不用在程序启动去循环请求， 只需要设计在收藏那 设置一个下拉刷新，请求收藏的所有本子{漫画}。

**Comment by niuhuan** [comment]
最新版实现了类似的功能，依靠轮询请求工作，所以现在限制了能加10部漫画。
