### ISSUE TITLE
希望能增加本地浏览器的功能

### ISSUE THREAD

**Issue by HIAMJ** [niuhuan/pikapika#117]
很喜欢这种连续向下的浏览器，能否增加一个导入本地压缩包的功能（现有的导入仅支持了由app导出的zip），本地含有图片的zip是没办法导入的

**Comment by niuhuan** [comment]
导出来的zip里面有一个js文件。里面包括了漫画/章节/图片三个层级的结构。 

您如果时间比较充裕, 可以进行逆向。组装一个zip, 导入到下载使用。

**Comment by HIAMJ** [comment]
感谢您的回复，有时间我会摸索一下的
