### ISSUE TITLE
大佬有兴趣开发hitomi.la的第三方吗

### ISSUE THREAD

**Issue by whghjyh** [niuhuan/pikapika#119]
hitomi.la（https://hitomi.la/）  是一个很强大的同类网站，支持很多语言，中文资源也非常的丰富，漫画方面有些资源甚至比E站更新都要迅速且全面
我看大佬好像还开发了许多其他的第三方，所以想请问一下。
我原来一直是在tachiyomi上使用hitomi.la的插件，由于被后者发现了所以插件就坏掉了。后来我找了许多的项目都不尽人意，可以参考一下：
https://github.com/tom5079/Pupil

pupil这个是hitomi的一个第三方，我当时用的时候感觉不大好，就只是把网页套了个壳并且优化了一下，最难受的是图片只能顺序加载，要看100页就只能等待前99页加载完
https://github.com/project-violet/violet

极其好用的hitomi第三方，语言也多，但是系统设置为中文会灰屏进不去。我联系了开发者，他们告诉我是字体包（由于开发者是韩国人，所以他们也不是很会搞这个）的问题，准备解决，但我跟进了几个版本都没有解决，只能更换系统字体进去，终究是放弃了。
如果大佬感兴趣希望大佬且有空能开发一下，让这样的好网站（除了广告有点多🌚）能让更多人使用。
另外我很喜欢这个项目，已star❤️。

**Comment by niuhuan** [comment]
没有API的多是网站套壳解析。
只能完成原本网站上就有的功能。官方支持分页，APP才能支持分页。

这个网站我并不知道它的接口签名方式，所以我一直没有开发。如果您比较期待，您可以整理一下接口文档，这样比较有助于我开发。

这个网站或许我可以实现免代理请求接口。


https://github.com/niuhuan/glxx/issues/1

**Comment by whghjyh** [comment]
抱歉，我不是计算机从业人员，也没有获取API的途径，貌似hitomi站长也没有在网站或其他地方公开可供使用的API，不过tachiyomi的插件库也许有您需要的东西https://github.com/tachiyomiorg/tachiyomi-extensions
或者我手上还有一份别的大佬在插件库插件失效后修补过的插件：
https://wwn.lanzoub.com/inrCQ02rm0vi
不知道能不能有所帮助

**Comment by niuhuan** [comment]
https://github.com/niuhuan/html-comic

开坑了

**Comment by shou-gakusei** [comment]
https://github.com/shou-gakusei/HitomiSemiautoDownloader/tree/0.0.1-alpha
如果你单纯想下下来在本地看的话（吐槽一下hitom自带的download功能实在是太狗屎了）
我现在就单纯的写了一个自动截图保存的脚本（虽然说个人认为带着hitomi这层ui会更有味道）
后面还得着重优化一下网络问题（校园网是这样的）

**Comment by shou-gakusei** [comment]
补充：
hitomi为了防止脚本现在换了第三方cdn+禁止跳转

**Comment by niuhuan** [comment]
我很早以前就已经停止维护 hitomi.la 的客户端了
