### ISSUE TITLE
<bug反馈>签名冲突

### ISSUE THREAD

**Issue by HIAMJ** [niuhuan/pikapika#120]
##### 手机机型为realme RMX3366 Android 12;
![Screenshot_2022-04-08-12-49-47-56_61a599d3932dc69](https://user-images.githubusercontent.com/50162569/162366972-31b68e73-85e4-4145-9b9d-07a04e148345.jpg)
![Screenshot_2022-04-08-12-42-18-51_bb8ece83317b06e](https://user-images.githubusercontent.com/50162569/162366655-5aea9d18-1155-4715-a1df-2ffffcb7f122.jpg)
![QQ图片20220408124419](https://user-images.githubusercontent.com/50162569/162366706-2e4a05da-edb8-4786-af55-643b6e7c2081.jpg)

**Comment by niuhuan** [comment]
有问题的是 v1.4.3 - 1.4.4 

 v1.4.5与1.0.0~1.4.0是兼容的

**Comment by HIAMJ** [comment]
明白了，感谢开发者的回复
