### ISSUE TITLE
怎么注册？windows1.4.5报错

### ISSUE THREAD

**Issue by weijiu233** [niuhuan/pikapika#125]
![image](https://user-images.githubusercontent.com/74433062/163712902-5a3cce67-b0ef-4865-aaed-bd8f12c949b2.png)
![image](https://user-images.githubusercontent.com/74433062/163712910-2a8f7ad8-6874-456f-95c8-93493bf31d5f.png)

**Comment by niuhuan** [comment]
暂时不支持http协议的代理，只支持socks5。请在您的的代理工具里查看，也可以试试留空代理，更换api分流。

**Comment by weijiu233** [comment]
留空貌似不行呢，api分流该怎么办？

**Comment by niuhuan** [comment]
并不是所有的地区都能通过分流解决。可以看看你的代理软件的socks5的端口是什么，用socks5://127.0.0.1:代理端口/。如果再不行的话就用手机端吧。

**Comment by xxxturbine** [comment]
手机端也出现这个情况怎么解决？
