### ISSUE TITLE
请问可以编译一份windows arm版本吗

### ISSUE THREAD

**Issue by luojunyuan** [niuhuan/pikapika#128]
在win11 arm64系统上，windows x86_64 版本无法打开

一般的 x86_64都是可以转译运行的样子但是pikapi似乎不行，运行没有反应。windows event事件管理器中也没有log

**Comment by niuhuan** [comment]
我不认为我能编译出windows/linux aarch64版本。

需要按照这个仓库的github actions 编译stable分支的flutter引擎。
https://github.com/go-flutter-desktop/engine-builds

**Comment by niuhuan** [comment]
gclient设置代理很迷，我没有成功下载过flutter的源代码
