### ISSUE TITLE
jasmine应用下载列表中无法使用删除功能

### ISSUE THREAD

**Issue by FLZBiss** [niuhuan/pikapika#129]
1.jasmine应用进入下载列表界面后，选择对应的下载对象点击删除，该对象并未从下载列表中移除。
2.希望jasmine应用有重新下载的功能，由于网络原因导致下载对象中途中断后，中断下载后的部分无法重新下载，造成部分图片无法显示

**Comment by niuhuan** [comment]
jasmine最新版已经修复了。点击刷新按钮可以重下。
