### ISSUE TITLE
pikapika windows 版双击后没有反应

### ISSUE THREAD

**Issue by ericvlog** [niuhuan/pikapika#135]
我下载了windows 版双击后没有反应？
我试了另一个jasmine ,那个就没问题。

**Comment by niuhuan** [comment]
双击放大图片？

**Comment by niuhuan** [comment]
我记得有几个选项来着，试试换个阅读器类型

**Comment by ericvlog** [comment]
我是说开不开软件。。。jasmine 就可以。

**Comment by niuhuan** [comment]
啊这，，，，，，。我能打开。

1.5.2，1.5.1都可以。你不是arm64Windows的话。

![20220522_211131](https://user-images.githubusercontent.com/20847533/169696808-953a8a89-a989-4e69-b0f2-ff58059522c9.jpg)

**Comment by niuhuan** [comment]
我也不能说出来个所以然，我用命令行运行也没有日志，在linux和mac上是有日志的。

pikapika和jasmine不同的是，pikapika是golang通过gcc编译，opengl渲染，应该用不上什么支持库。

jasmine是rust通过msvc编译。

**Comment by ericvlog** [comment]
> 我也不能说出来个所以然，我用命令行运行也没有日志，在linux和mac上是有日志的。
> 
> pikapika和jasmine不同的是，pikapika是golang通过gcc编译，opengl渲染，应该用不上什么支持库。
> 
> jasmine是rust通过msvc编译。

我也试了 1.51 也打开不到完全没反应， jasmine 就可以。。。。我的是 x86_64bit windows.
有可能你所说的这个和jasmine 是不同语言写的吧。
谢谢

**Comment by niuhuan** [comment]
我试了我3台电脑，甚至包括一台干净的虚拟机。

额，都没有问题。

只能给您点建议吧。
- 安装 [vcredist2015-2019](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)
- 显卡是否能用
- 是否解压了再使用
- 是否有读写权限
-

**Comment by WeihuaGu** [comment]
我的一样情况，windows ubuntu都不行。好在ubuntu报了错误：
```sh
2022/06/23 23:19:41 /home/runner/work/pikapika/pikapika/go/pikapika/database/properties/properties.go:39 record not found
[0.072ms] [rows:0] SELECT * FROM `properties` WHERE `k` = "full_screen" AND `properties`.`deleted_at` IS NULL ORDER BY `properties`.`id` LIMIT 1
creating glfw window: VersionUnavailable: EGL: Failed to create context: Arguments are inconsistent
```
```sh
glxinfo | grep 'OpenGL version'
OpenGL version string: 2.1 Mesa 21.2.6
```

所以应是opengl版本问题上？

**Comment by niuhuan** [comment]
根据你的日志, 我在引擎仓库里找到了两个issue, 开发者的提示似乎是, 编译不使用GL的版本再运行。

https://github.com/go-flutter-desktop/go-flutter/issues/595
https://github.com/go-flutter-desktop/go-flutter/issues/368

**Comment by niuhuan** [comment]
已经按照提示编译了，如果是硬件版本的问题我是没有办法解决的。

https://github.com/niuhuan/pikapika/releases/tag/v1.5.3

windows--opengl_none.zip

**Comment by WeihuaGu** [comment]
感谢，还是不行。这应该是上游的问题吧。

**Comment by niuhuan** [comment]
你的电脑比较旧吗？

**Comment by WeihuaGu** [comment]
07年的电脑，我花一共500块买的二手。我都用了七年多了,775针的cpu,intel 的集显。
