### ISSUE TITLE
编译windows版本会报错，首页一个星之卡比+皮卡丘，然后不动了

### ISSUE THREAD

**Issue by hugetiny** [niuhuan/pikapika#138]
编译时候报一堆空安全错误，这个可以忽略的话，下面的导致windows上windows客户端跑不起来

flutter: DEPTH : 1
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method flatInvoke on channel method)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      Method.loadProperty (package:pikapika/basic/Method.dart:28:12)
<asynchronous suspension>
#2      initAutoClean (package:pikapika/basic/config/AutoClean.dart:16:7)
<asynchronous suspension>
#3      _InitScreenState._init (package:pikapika/screens/InitScreen.dart:58:5)
<asynchronous suspension>

**Comment by niuhuan** [comment]
空安全错误是因为flutter的版本依赖造成的，依赖还没有跟进，换成2.10.3就不会了

**Comment by niuhuan** [comment]
如果只是想编译，请移步我写的nhentai-cross，并参考github Actions 。

**Comment by hugetiny** [comment]
nhentai-cross里面也没写编译相关的文档。
本地编译和github actions有关吗？

**Comment by hugetiny** [comment]
> 如果只是想编译，请移步我写的nhentai-cross，并参考github Actions 。
nhentai-cross里面也没写编译相关的文档。
本地编译和github actions有关吗？

**Comment by niuhuan** [comment]
> > 如果只是想编译，请移步我写的nhentai-cross，并参考github Actions 。
> 
> nhentai-cross里面也没写编译相关的文档。 本地编译和github actions有关吗？

github actions 属于自动集成工具, 里面有具体的编译步骤。 主要jobs

您首先要安装golang ,futter。
安装hover。
然后运行hover run

**Comment by niuhuan** [comment]
手机端需要进入go/mobile
然后运行 gomobile bind
最后运行 flutter run
