### ISSUE TITLE
有大佬能编译个iOS版吗？

### ISSUE THREAD

**Issue by noir1216** [niuhuan/pikapika#14]
秋梨膏
小白不会编译

**Comment by niuhuan** [comment]
ios开发者才能编译

一年99美元

**Comment by niuhuan** [comment]
可以试试 https://github.com/fanyuecheng/Pica

**Comment by noir1216** [comment]
> 可以试试 https://github.com/fanyuecheng/Pica

嗯，我知道这个，但是这个无法选择分流，只能使用VPN连接。

**Comment by noir1216** [comment]
是将该项目的iOS文件夹导入xcode里进行编译吗？

**Comment by niuhuan** [comment]
如果你是苹果开发者 (给苹果交过钱), 安装go flutter hover , 按照文档里运行sh,  然后运行 flutter build ipa

**Comment by niuhuan** [comment]
我自己仓库有自动构建功能的，也解决不了没有苹果开发者账号的问题。

**Comment by JONREAN2** [comment]
> 我自己仓库有自动构建功能的，也解决不了没有苹果开发者账号的问题。

我有 我可以签名。。就是没有ipa包

**Comment by niuhuan** [comment]
我没有办法打ipa包，flutter不支持没有签名的ipa的构建，网上有直接压缩zip改名成ipa的方法，但是能不能用并不清楚。

如果你想真机运行，xcode golang flutter gomobile 都装好之后运行sh bind-ios.sh 

手机连接mac，再运行flutter run 即可

**Comment by niuhuan** [comment]
我试一下网上的方法，你稍等一下

**Comment by JONREAN2** [comment]
> 我试一下网上的方法，你稍等一下

哇 麻烦大佬了 要是可以的话，能帮忙生产一个ipa包么？其实我只会给ipa签名。。。非常感谢了

**Comment by niuhuan** [comment]
请你留下一个邮箱, 收到我的邮件之后从issue中删除

**Comment by JONREAN2** [comment]
> 请你留下一个邮箱, 收到我的邮件之后从issue中删除
ouyangshaogong7230@outlook.com

**Comment by JONREAN2** [comment]
拜谢

> 请你留下一个邮箱, 收到我的邮件之后从issue中删除

拜谢拜谢

**Comment by niuhuan** [comment]
已经发好了,  你试一下签名, 如果可以的话可以反馈一下

**Comment by JONREAN2** [comment]
> 已经发好了, 你试一下签名, 如果可以的话可以反馈一下

没有收到啊.....我邮箱有问题了可能。。。可以发这个吗？ 1829570217@qq.com

**Comment by niuhuan** [comment]
额

**Comment by noir1216** [comment]
> 已经发好了, 你试一下签名, 如果可以的话可以反馈一下

老哥能转发一份吗ipa包？我是越狱设备。

**Comment by JONREAN2** [comment]
> 额

不行，安装不了，显示ipa文件错误

**Comment by niuhuan** [comment]
> > 已经发好了, 你试一下签名, 如果可以的话可以反馈一下
> 
> 老哥能转发一份吗ipa包？我是越狱设备。

打出来的ipa并不能用  , 参考文章 <Flutter：实现iOS无证书打包ipa>

**Comment by fanyuecheng** [comment]
必须得交了钱的开发者账号或者该开发者账号加入交了钱的开发者团队下，才能打包。
用七天的免费证书是没法打包的，直接改zip为ipa以前可能行，但是现在是不行的。
我一开始用公司证书打包，但是不被允许了，也不再提供ipa包

**Comment by Z-fly** [comment]
> 必须得交了钱的开发者账号或者该开发者账号加入交了钱的开发者团队下，才能打包。
> 用七天的免费证书是没法打包的，直接改zip为ipa以前可能行，但是现在是不行的。
> 我一开始用公司证书打包，但是不被允许了，也不再提供ipa包

所以你那个项目就再也没法打包了吗？
我想到一个方法，用一台越狱的设备，安装后，进行砸壳，然后导出，应该就行了。

**Comment by niuhuan** [comment]
> > 必须得交了钱的开发者账号或者该开发者账号加入交了钱的开发者团队下，才能打包。
> > 用七天的免费证书是没法打包的，直接改zip为ipa以前可能行，但是现在是不行的。
> > 我一开始用公司证书打包，但是不被允许了，也不再提供ipa包
> 
> 所以你那个项目就再也没法打包了吗？
> 我想到一个方法，用一台越狱的设备，安装后，进行砸壳，然后导出，应该就行了。

主要没证书，他不让打包，也不让真机调试，越狱的不知道能不能usb安装。

**Comment by JONREAN2** [comment]
> > 必须得交了钱的开发者账号或者该开发者账号加入交了钱的开发者团队下，才能打包。
> > 用七天的免费证书是没法打包的，直接改zip为ipa以前可能行，但是现在是不行的。
> > 我一开始用公司证书打包，但是不被允许了，也不再提供ipa包
> 
> 所以你那个项目就再也没法打包了吗？
> 我想到一个方法，用一台越狱的设备，安装后，进行砸壳，然后导出，应该就行了。

砸壳前提是你先安装 哪个ipa吧

**Comment by Z-fly** [comment]
> > > 必须得交了钱的开发者账号或者该开发者账号加入交了钱的开发者团队下，才能打包。
> > > 用七天的免费证书是没法打包的，直接改zip为ipa以前可能行，但是现在是不行的。
> > > 我一开始用公司证书打包，但是不被允许了，也不再提供ipa包
> > 
> > 
> > 所以你那个项目就再也没法打包了吗？
> > 我想到一个方法，用一台越狱的设备，安装后，进行砸壳，然后导出，应该就行了。
> 
> 砸壳前提是你先安装 哪个ipa吧

如果不能真机调试的话，那就凉了

**Comment by noir1216** [comment]
大佬们看看这个帖子的方法是否能使用？
https://hello-david.github.io/archives/61787736.html

**Comment by niuhuan** [comment]
@noir1216  打完了, 不过是debug包
