### ISSUE TITLE
为啥要多一层go-flutter/gomobile

### ISSUE THREAD

**Issue by hugetiny** [niuhuan/pikapika#140]
flutter新人问题，按理说flutter都支持全平台了，为啥要多一层go-flutter/gomobile在架构里？
或者说go在项目中起什么作用？

**Comment by niuhuan** [comment]
编程思想方面的问题，您应该到flutter相关社区去提问，或是使用搜索引擎，会有更好的回答。您也可以使用以下关键字
《为什么安卓或Flutter项目里会有Native部分》
