### ISSUE TITLE
请求为windows版增加锁定功能和exe图标

### ISSUE THREAD

**Issue by ScarletS5** [niuhuan/pikapika#142]
请求为windows版增加锁定功能和exe图标：

锁定功能可以参考Telegram，在启动时、手动锁定后或者超过一定时长没有操作情况下自动锁定：
  启动时：
![QQ截图20220608191720](https://user-images.githubusercontent.com/98156948/172606079-4ef46892-bf79-46cb-868f-2fc929e22922.jpg)

  手动锁定：
![image](https://user-images.githubusercontent.com/98156948/172606438-c9bf2ce8-cc70-4040-b474-828976b80e55.png)

  超时锁定：
![QQ截图20220608192919](https://user-images.githubusercontent.com/98156948/172606542-3027dacd-c8d2-4d59-af17-dde1e021d109.jpg)
（锁定功能可以有效防止软件被人打开导致社死）

windows版本软件没有exe图标，直接添加到win10磁贴里不太美观，请求增加exe图标：
![image](https://user-images.githubusercontent.com/98156948/172606847-28bcc469-8405-4649-ab2c-49553bf004d6.png)

![image](https://user-images.githubusercontent.com/98156948/172606903-a2a2b7bd-1a61-49d1-8097-bb1d10c9ebc7.png)

目前可以通过生成快捷方式，给快捷方式更改图标来解决：
![image](https://user-images.githubusercontent.com/98156948/172607187-1f4fe65f-6a44-434e-8b2e-b1ce9c7c41d6.png)

![image](https://user-images.githubusercontent.com/98156948/172608054-9955c035-0fc6-4f22-a476-09e3682a806c.png)

**Comment by rexcape** [comment]
可以先将软件升级到最新版本。最新版本软件中的 exe 文件有图标，添加到开始菜单后可以正常看到图标。
![image](https://user-images.githubusercontent.com/53886131/178110879-7def791f-4c99-497c-a48e-56b1e19c63b6.png)
![image](https://user-images.githubusercontent.com/53886131/178110894-a5a40ed6-4e24-4fec-bcdd-55c9a587b643.png)

**Comment by niuhuan** [comment]
超时锁定已经加了，现在但是只支持窗口最小化以后，不支持静置超时
