### ISSUE TITLE
直接 flutter run --release 编译吗？

### ISSUE THREAD

**Issue by wzh4464** [niuhuan/pikapika#144]
M1 Mac 编译之后只能看见开始的比卡丘

**Comment by niuhuan** [comment]
不能, 而且不能原生支持m1。flutter最多支持到2.10.3。不支持flutter3。

为防止被商业使用, 这个仓库的代码是不全的。您可以试试这个仓库 https://github.com/niuhuan/nhentai-cross


- 安装golang 1.17
- 安装flutter2.10.3
- 安装go-flutter hover
- 最后运行 hover run

**Comment by niuhuan** [comment]
两个仓库技术架构完全一样, 只是后端不一样。
