### ISSUE TITLE
封面和点击阅读后图片加载失败

### ISSUE THREAD

**Issue by zk563966712** [niuhuan/pikapika#148]
显示红叉，之前已经缓存过的封面显示没问题，之前已下载的漫画也没问题。切换网络和挂梯子解决不了，应用显示占用2g多的空间，全清重新登陆后问题解决。
米10 8+256，安卓12。

**Comment by niuhuan** [comment]
@zk563966712  更新之后出的问题？

**Comment by zk563966712** [comment]
更新后出现的。现在重新下载了2.36g的漫画，仍未重现这个问题。应该已经解决了
