### ISSUE TITLE
留言板

### ISSUE THREAD

**Issue by niuhuan** [niuhuan/pikapika#149]
留言板

如果您的消息希望加密，请将您想说的内容使用熊曰加密放在这里。

http://hi.pcmoe.net/index.html

**Comment by euXnZv** [comment]
熊曰：呋有非噗魚嗅麼嗡呱果咯取物你更會噗蜂達唬擊呱樣嚁盜蜂麼常呦捕人擊嘿怎取哈蜜覺怎歡嘶噔嘶很萌象呆嘍現覺和捕非告嗄魚啽森物現嗒洞動意拙呆意雜常吃

**Comment by Minori-ty** [comment]
你用go做了什么？我看到好像就是只用go做了ci？

**Comment by niuhuan** [comment]
> 你用go做了什么？我看到好像就是只用go做了ci？

想知道go做了什么去看 [nhentai](https://github.com/niuhuan/nhentai-cross) 的源码

**Comment by lmlx001** [comment]
熊曰：呋食食冬堅意冬怎出常冬喜現寶吖告萌破會森吖歡噗嗡蜜吃爾萌歡山爾嗒歡嚄你住樣嚁你嗅誒覺爾啽蜂誒襲唬更怎歡嚄嗷常氏動取冬歡嚄嗅嘍嗄食發象哞盜取呆哞樣象嗅誘哈麼嗷我噔

**Comment by niuhuan** [comment]
> 熊曰：呋食食冬堅意冬怎出常冬喜現寶吖告萌破會森吖歡噗嗡蜜吃爾萌歡山爾嗒歡嚄你住樣嚁你嗅誒覺爾啽蜂誒襲唬更怎歡嚄嗷常氏動取冬歡嚄嗅嘍嗄食發象哞盜取呆哞樣象嗅誘哈麼嗷我噔

点菜单，换浏览器类型

**Comment by lmlx001** [comment]
禁漫收藏夹显示空白，且希望在预览页添加信息比如收藏数，页数等等

**Comment by niuhuan** [comment]
> 禁漫收藏夹显示空白，且希望在预览页添加信息比如收藏数，页数等等

前几天测试过，官方app没有显示收藏夹信息。不知道是不是换接口了，过两天再抓包一下。

**Comment by lmlx001** [comment]
哔咔下载列表  希望能加上点击作者详情页

**Comment by Minori-ty** [comment]
更新app可以做成在线更新吗？大概应该是断点下载，调用安装。

**Comment by niuhuan** [comment]
> 更新app可以做成在线更新吗？大概应该是断点下载，调用安装。

我不喜欢这样, 而且还要做安卓的通知栏, 还要适配架构

**Comment by Minori-ty** [comment]
> 

那你可以在收藏页那里弄一个批量下载吗？

**Comment by Cyndibaby** [comment]
注册账号好难啊...

**Comment by niuhuan** [comment]
> 注册账号好难啊...

账号, 名字 , 密码, 都设置成8位以上, 字母加数字
