### ISSUE TITLE
一些issues和features request

### ISSUE THREAD

**Issue by hospotho** [niuhuan/pikapika#152]
使用版本：[pikapika-v1.5.6-flutter_3.0.4-android-arm64.apk](https://github.com/niuhuan/pikapika/releases/download/v1.5.6/pikapika-v1.5.6-flutter_3.0.4-android-arm64.apk)
android版本：12

### Issues
1. 導出介面選擇和tag重疊
![image](https://user-images.githubusercontent.com/50175140/179599942-72f8e43d-567a-4ef9-b9cf-1df646cd168c.png)

2. 排序選項功能重複
![image](https://user-images.githubusercontent.com/50175140/179599142-4727b39c-6454-40eb-90bb-f8353135144e.png)

3. 瀏覽記錄刪除時封面沒有更新(孔明用了原來位置忍殺的封面)
![image](https://user-images.githubusercontent.com/50175140/179607869-4e1f1878-e32e-43ab-8f37-24aa697d7ddb.png)

4. 部分現有操控方式無法在閱讀器更改設定，可能全都加一個動作(下拉？)來調出UI

### Features request
1. 搜索時不顯示"全分類"，僅顯示搜索的關鍵字
![image](https://user-images.githubusercontent.com/50175140/179607051-2b14bcf4-f8bf-440c-8f25-76fdc755248c.png)
![image](https://user-images.githubusercontent.com/50175140/179607463-9746ff16-add5-463c-afd1-88bda987496c.png)

2. 操控方式加入原版的L型區域控制，"上""左"上一頁、"下""右"下一頁

3. 閱讀器預載入圖片，自動載入的數量(2-20自己選？)也放進設定

4. 在主介面返回時彈出一個確定視窗，以防誤觸返回鍵關閉應用

5. 封面一點就能看，不用先長按再選預覽

6. 沒看源碼，但如果禁止截圖和禁止顯示在任務視圖是兩個不同的功能，希望能分開一下

7. 希望導入能直接加入圖片資料夾，當作圖片、漫畫閱讀器用

其實就是想用原版的功能看漫畫，結果發現原版沒有導入就找到這。除了有點小問題，這UI比原版看起來好多了，給star了以後翻源碼學習一下

**Comment by niuhuan** [comment]
6 不能分开使用

**Comment by niuhuan** [comment]
1. 不影响使用，应该暂时不会解决
2. 参数传与不传的区别，官方也如此设计，所以没有加以区分
3. 已经修复
4. 不好实现、暂时先放入TODOList
5. 会产生手势分歧，其他列表模式笔记哦啊明显
6. -
7. 不好实现、暂时先放入TODOList
