### ISSUE TITLE
你好，现在flutter已经稳定支持桌面端了，是不是理论上可以拜托掉go-flutter了

### ISSUE THREAD

**Issue by ziyouzy** [niuhuan/pikapika#154]
我就是随便问问，我似乎入门的时候没赶上大佬们用go-flutter的时代
上午没看相关文章的时候直接进行了flutter run -d windows但是显然是不行的😂😂😂

**Comment by ziyouzy** [comment]
是我刚才对go-flutter理解的有问题，把他看作是个sdk思路一下就打开了，go-flutter依然是必须的通过，因为需要通过这sdk实现诸如文件io之类的底层操作，而go-flutter这个类似sdk的东西最大的意义就是在于跨端，就不用分别去用java或者swift写各自的底层逻辑了

**Comment by niuhuan** [comment]
您可以看下这个

https://github.com/niuhuan/pikapika/issues/144

**Comment by niuhuan** [comment]
思路很对，原生flutter的话，windows,  Linux 这一些系统交互很麻烦，写错的话很容易崩溃，多线程也存在问题。

**Comment by ziyouzy** [comment]
学习了，感谢大佬调教🤣
似乎go-flutter是go语言的一种第三方gui拓展(其实都是google自家的)
如果把他理解成是flutter的一种用于支持go语言的插件package技术，虽然说的过去但是却会把一切都搞复杂了。
他是属于go技术栈的一部分

**Comment by niuhuan** [comment]
flutter3.0, go-flutter 还没有完全适配, 跟空安全没有关系。可以去[go-flutter-desktop](https://github.com/go-flutter-desktop/go-flutter)那里看一下。自己尝试一下。

**Comment by ziyouzy** [comment]
谢谢，感觉自己还有好多东西要学🤢
