### ISSUE TITLE
有的漫画可以看，有的全是红叉

### ISSUE THREAD

**Issue by oto1o1o** [niuhuan/pikapika#156]
![Screenshot_2022-08-13-16-10-29-785_niuhuan.pikapika.jpg](https://user-images.githubusercontent.com/111174279/184475689-df86aa1f-1e02-4144-9193-8b5d6af9ddfd.jpg)![IMG_20220813_161139.jpg](https://user-images.githubusercontent.com/111174279/184475694-d6c4d54f-9bb7-4993-a2db-ed521b10fe16.jpg)

**Comment by niuhuan** [comment]
挂个梯子，或者切换下图片分流

**Comment by Smile8848** [comment]
> 挂个梯子，或者切换下图片分流

一样的情况 而且只有之前看过的封面能正常显示 内容全部都是x 官方app可以正常浏览

**Comment by Smile8848** [comment]
> 挂个梯子，或者切换下图片分流

卸载重新安装解决 应该程序哪里有问题，这种情况出现挺多了

**Comment by niuhuan** [comment]
> > 挂个梯子，或者切换下图片分流
> 
> 卸载重新安装解决 应该程序哪里有问题，这种情况出现挺多了

应该是旧版升新版的问题吧，之前有一版是这样的

**Comment by Smile8848** [comment]
> 

之前确实是这样 但这次我并没有升级
