### ISSUE TITLE
希望加一个关掉翻页动画的选项

### ISSUE THREAD

**Issue by lyb627084437** [niuhuan/pikapika#159]
想要用墨水屏阅读器来看(屏幕比起手机能稍微大点，用平板的话又太重了)，但对于墨水屏的刷新率来说，翻页动画会严重影响体验。

**Comment by niuhuan** [comment]
设置里有

**Comment by lyb627084437** [comment]
> 设置里有

是我傻了，设置里有个取消音量键或键盘翻页动画，我寻思着用也不用这俩翻页啊，所以就没开。。。刚才试了下，翻页动画确实没了

**Comment by niuhuan** [comment]
你也可以设置成点按屏幕翻页， 如果不习惯音量键的话
