### ISSUE TITLE
希望适配1.5k分辨率

### ISSUE THREAD

**Issue by yzx23333** [niuhuan/pikapika#160]
在k50u也就是2712×1220，dpi为480的分辨率下，主页会出现排版问题，望修复
![IMG_20220826_124350](https://user-images.githubusercontent.com/69612876/186823940-f295f1a4-af9d-4fcd-941c-8840f513a6ec.jpg)

**Comment by niuhuan** [comment]
每个方块的大小与分辨率没有关系, 跟长宽比有关系, 屏幕越方, 方块越大.

**Comment by yzx23333** [comment]
那这块屏是20:9，感觉也没什么问题啊，长宽比和常见机型一样的
所以请问作者您会修复这个问题吗

**Comment by niuhuan** [comment]
还没有想好怎么办🙃

**Comment by niuhuan** [comment]
在最新版设置种可以设置成3列可以解决。

**Comment by yzx23333** [comment]
我个人测试，设置成三列后依旧只能显示两列但图标缩小了
设置成4列后如下图所示，上面这三个似乎没有算作列表
![Screenshot_2022-09-11-01-17-24-526-edit_niuhuan pikapika](https://user-images.githubusercontent.com/69612876/189494519-983a99ef-67d3-4b4a-9821-5b4b90ffe0fc.jpg)
设置成两列图标则会变大，但排行榜，随机，游戏这三个没有变化

**Comment by niuhuan** [comment]
嗷，需要再打一下

**Comment by yzx23333** [comment]
1.5.12版本回报：3列的情况下依旧显示两列，和我发的第一张图情况一致。4列看起来还行，上方图标缩小。下图是这个版本4列的效果
![Screenshot_2022-09-18-21-00-36-594-edit_niuhuan pikapika](https://user-images.githubusercontent.com/69612876/190903356-fceb0f2e-1544-433e-8e5b-ccbd865d1f36.jpg)
望作者能继续改进出三列的版本。
（顺便说一句，列数自动的情况和3列一致。）

**Comment by niuhuan** [comment]
天呐。。。

**Comment by niuhuan** [comment]
1.5.13已经修改

**Comment by yzx23333** [comment]
1.5.13版本测试所有数量的列显示效果都很不错了，作者辛苦了😙
