### ISSUE TITLE
iPhone 8上用客户端会产生渲染问题

### ISSUE THREAD

**Issue by NekoMua** [niuhuan/pikapika#163]
小屏幕手机上的字体渲染，在滑动的时候会莫名其妙便细，感觉是次像素渲染问题

**Comment by niuhuan** [comment]
我暂时并不知道该如何修复它

**Comment by wc7086** [comment]
> 我暂时并不知道该如何修复它

这个可能是 flutter 的问题，去翻了一下 issues，太多了，我还没找到和这个问题一样的
