### ISSUE TITLE
[功能建议]增加对官方版软件的下载内容的导入进本软件的功能

### ISSUE THREAD

**Issue by Mo-Yuxi** [niuhuan/pikapika#170]
对于一些使用了很长时间官方软件的用户可能存在大量的已下载漫画，而官方版软件的下载的存储结构和本软件的下载缓存打包结构相似，是否可以新增功能对指定目录下的官方版下载内容进行导入

**Comment by niuhuan** [comment]
有没有文档，或者资料？是否需要root?

**Comment by niuhuan** [comment]
看似可以导入，只读取图片文件。缺少的信息使用接口再次请求回来似乎可行。☺️，任务会加入todolist，后面的迭代会考虑加入。

**Comment by Mo-Yuxi** [comment]
感谢，期待后续版本的发布

**Comment by niuhuan** [comment]
如果是只有章节id没有漫画id，上面的想法是不行的。但是可以把这个文件夹当作缓存文件夹，手动去pikapika里点一下下载，然后从这里检测有没有缓存

**Comment by niuhuan** [comment]
可以了，新版，选使用下载缓存，选那个files文件夹，然后你再下载同样的漫画就会特别快，其实就是复制图片到软件里

**Comment by Mo-Yuxi** [comment]
可行，感谢大佬

**Comment by YiFang172** [comment]
那我这接近一千本漫画都只能一个一个导入吗_(´ཀ`」 ∠)__

**Comment by niuhuan** [comment]
没root权限拿不到sqlite、不确定……额 开发难度也大
