### ISSUE TITLE
方便分享下怎么结合gomobile和flutter的嘛?

### ISSUE THREAD

**Issue by zohar-soul** [niuhuan/pikapika#173]
翻了下源码好像没看到相关的部分, 这块的实践资料又相对比较少....

**Comment by niuhuan** [comment]
参考我写的 nhentai-cross

**Comment by niuhuan** [comment]
https://github.com/niuhuan/nhentai-cross

里面有完整代码

**Comment by zohar-soul** [comment]
> 参考我写的 nhentai-cross

多谢, 我去看一下
