### ISSUE TITLE
不太懂得如何安装新版本（我是安卓）

### ISSUE THREAD

**Issue by Unnicoo** [niuhuan/pikapika#174]
打开网站，没有找到安装的链接在哪里，最下面的地方有好多个可以下载的文件，难道要都下载吗？不好意思，完全是小白，所以搞不懂

**Comment by Unnicoo** [comment]
找到了，原来是下面那一串里面的第三个，之前看到第一个后缀是dmg就害怕了，没想到每一个后缀都不一样，第三个刚好是apk
感谢作者

**Comment by niuhuan** [comment]
hhhhh 兄台注意身体
