### ISSUE TITLE
求助！该安装包未包含任何证书

### ISSUE THREAD

**Issue by 777wtmsb** [niuhuan/pikapika#177]
我手机是荣耀v20系统Android 10非鸿蒙，昨天还从1.5.10升级到1.5.14，今天想回滚下版本却发现所有版本的apk安装时都报这个错误，请问是咋回事？？
PS.安全设置该关的都关了

**Comment by niuhuan** [comment]
你可以试试删除掉app再安装
可能是只有鸿蒙系统有问题？

**Comment by 777wtmsb** [comment]
> 你可以试试删除掉app再安装 可能是只有鸿蒙系统有问题？

额我不是鸿蒙系统，，不过不知道为啥我用手机下的apk安装会报这个错误，换电脑下载然后传到手机再安装就没问题了，总之问题是解决了。
PS.图片服务器是下一个版本才能弄好吗？现在啥图片都加载不出来

**Comment by niuhuan** [comment]
安卓的话选分流3挂代理
