### ISSUE TITLE
下载完成后不显示图标也无法打开

### ISSUE THREAD

**Issue by arqueidist** [niuhuan/pikapika#181]
![Screenshot_20230117_164900_com.android.packageinstaller.jpg](https://user-images.githubusercontent.com/102496935/212851679-4d2ad800-32e7-4017-9ac5-6404b1b50171.jpg)

**Comment by arqueidist** [comment]
> 手机型号？系统版本？对应安卓版本？
> 
> 应该是系统版本太高之类的？ 

荣耀v10，EMUI9，安卓9

**Comment by niuhuan** [comment]
试试带old的，并且选择正确的架构呢
