### ISSUE TITLE
功能请求: 浏览动图

### ISSUE THREAD

**Issue by zam157** [niuhuan/pikapika#182]
目前似乎不支持动图浏览功能

**Comment by niuhuan** [comment]
没遇到有动图的漫画

**Comment by zam157** [comment]
> 没遇到有动图的漫画

漫画名: **催眠で家族でＨな♥ちゅーばー生活 全CG（去口罩）** 里面有一篇动图的章节
![Screenshot_2023-01-28-07-40-26-349_niuhuan.pikapika.jpg](https://user-images.githubusercontent.com/24277775/215226543-0c7b85c2-372f-4806-a2cd-d2180ef6936f.jpg)

以我的经验看其实有很多漫画中间会穿插动图的

**Comment by niuhuan** [comment]
刚看了一下无码动图里面的图片是jpeg格式的， 所以不会动。还是需要定位到gif。才能调试

**Comment by niuhuan** [comment]
官方客户端的也是jpeg吧？

**Comment by zam157** [comment]
看来我的经验有误🤔 既然官方APP都没有的功能实现了确实也没意义

**Comment by niuhuan** [comment]
> 看来我的经验有误🤔 既然官方APP都没有的功能实现了确实也没意义

他可能是吧图进行压缩了

**Comment by zam157** [comment]
暂时close了，目前来看确实没找到动图的场景
