### ISSUE TITLE
「功能请求」希望能上MD3

### ISSUE THREAD

**Issue by zjm54321** [niuhuan/pikapika#184]
希望能把ui重绘成 MD you 的样子，不知道实现起来是否困难

**Comment by niuhuan** [comment]
没有接触过MD3这块，这个软件的所有UI都没有做任何渲染修改，都是flutter自带的组件。

如果能直接套用md3组件是最好的。

如果您有demo或者文档或者是设计，我很乐意软件变得更美观。

😀😀😀😀😀😀

**Comment by niuhuan** [comment]
刚才试了直接开启flutter3的md3功能, 丑的一P。

**Comment by PIut02** [comment]
这是官方的demo和文档，希望能有帮助
https://m3.material.io/develop/flutter
https://github.com/flutter/samples/tree/main/material_3_demo

**Comment by hosxy** [comment]
别吧，md3丑的要死，各种无脑大圆角，信息密度还很低

**Comment by niuhuan** [comment]
将来可能也不支持MD3，我也认为MD3很丑。
