### ISSUE TITLE
请问是否会增加安卓版字体大小

### ISSUE THREAD

**Issue by Yothewan** [niuhuan/pikapika#185]
您好，请问一下，在计划中的功能里看见有为桌面环境下设置文字大小的打算，不知道安卓版是否也能增加字体调节啊？现在整体看起来都偏小，对眼睛不太友好T T

**Comment by niuhuan** [comment]
软件字体，基本已经固定，调节起来比较繁杂，而且不好设置个分类。一段时间内不会加这个设置

**Comment by Yothewan** [comment]
了解，太遗憾了

**Comment by niuhuan** [comment]
已经开始做了

**Comment by niuhuan** [comment]
可以尝试一下最新版本的resizeful构建，实验性功能，将来可能会删掉或这合并
