### ISSUE TITLE
旧版本下载没法导入到新版本？

### ISSUE THREAD

**Issue by Nemo1166** [niuhuan/pikapika#188]
如题，最近一次更新由于更换了appid故不能覆盖安装。导出的旧版本下载内容只能以阅读模式打开，其余支持导入的格式均为发电后可用。

**Comment by niuhuan** [comment]
导出zip，再导入新的应该可以

**Comment by Nemo1166** [comment]
> 导出zip，再导入新的应该可以

也就是说不发电就没法从旧版本导入到新版本，是这样吗？

**Comment by niuhuan** [comment]
不发电也可以导入导出
发电可以签到获得

**Comment by Nemo1166** [comment]
已解决，感谢
