### ISSUE TITLE
望采纳

### ISSUE THREAD

**Issue by THyouka** [niuhuan/pikapika#189]
希望能增加阅读时屏幕旋转功能

**Comment by niuhuan** [comment]
你可以把设备的重力感应自动旋转打开试试？

**Comment by THyouka** [comment]
感谢采纳

> 你可以把设备的重力感应自动旋转打开试试？

感谢回复。主要是侧躺时手机竖立放置，重力感应无法锁定横屏状态！

**Comment by niuhuan** [comment]
可以临时锁定设备旋转
