### ISSUE TITLE
单个网络导出，在同一IP段下输入IP地址后客户端反馈导出失败

### ISSUE THREAD

**Issue by JayJ-Huang** [niuhuan/pikapika#192]
第一个问题：最新版客户端。单个网络导出，在同一IP段下输入IP地址后客户端反馈导出失败。
第二个问题：官方压缩形式PC压缩软件能解压吗？
第三个问题：有没有比较快捷方便的发电方式？签到发电需要多久？

**Comment by JayJ-Huang** [comment]
在哪里签到？客户端看不到！

**Comment by niuhuan** [comment]
1： 请检查网络原因
2： zip在PC能解压，能看
3： 去TG频道里，第二条消息找到群，签到

**Comment by JayJ-Huang** [comment]
1： 请检查网络原因
re：后来试了用另外手机浏览器输入IP地址，能开始导出进程，但显示下载失败，PC上又换了浏览器，IE连接不上，Chrome跟QQ浏览器也一样连接不上，APP显示导出失败。
2： zip在PC能解压，能看
re：官方的PKZ好像没办法在PC解压。
3： 去TG频道里，第二条消息找到群，签到
re：是官方TG还是咋们的TG（咋们TG没看到）。官方TG加了大群和IOS群，不知道怎么签到，求指教！感谢！

**Comment by niuhuan** [comment]
这个是第三方客户端，跟官方没有任何关系。去本仓库的releases里面加群和频道。

导出到其他设备不是给你下载的。而是让你用其他设备上用pikapika导入，方便pc上缓存的内容导入手机。

**Comment by niuhuan** [comment]
不过您的想法很独特，下载zip是我没想过的道路。

**Comment by JayJ-Huang** [comment]
懂了，网络传输需要双方有pikapika。
已经在release里找到签到入口并签到，导出了zip。
感谢大佬解答，希望大佬可以考虑直接全部图片形式的zip压缩，通用性比较好。

**Comment by niuhuan** [comment]
最新版支持导出图片.zip

**Comment by JayJ-Huang** [comment]
我是1.6.7最新版哦。是否picture文件夹里的就是图片？要改后缀再打开吧？

**Comment by JayJ-Huang** [comment]
本地纯JPG的本子压缩成zip也无法导入APP中观看~这个可以解决吗

**Comment by niuhuan** [comment]
应该是选最后一个选项，导出的zip可以用其他阅读器直接看。不支持导入其他阅读器生成的zip

**Comment by niuhuan** [comment]
你要是很想导入pikapika看，需要自己编排
