### ISSUE TITLE
能否新增一个导入历史记录的功能

### ISSUE THREAD

**Issue by wuyu112233** [niuhuan/pikapika#196]
能否通过导入pica的db文件，实现历史记录导入pika
位于data/data/com.picacomic.gregata/databases/com_picacomic_fregata.db这个文件内，
的第二个部分DB_COMIC_VIEW_RECORD_OBJECT

**Comment by niuhuan** [comment]
这是个不错的想法，但是我并没有root的安卓机，或许需要很久才能实现
