### ISSUE TITLE
发电功能似乎失效

### ISSUE THREAD

**Issue by zfh020625** [niuhuan/pikapika#197]
绑定了账号但是发电里选择“我曾经发了电”显示full

**Comment by zfh020625** [comment]
> 绑定了账号但是发电里选择“我曾经发了电”显示full

更正一下，错误代码似乎是fail
error code：fail

**Comment by niuhuan** [comment]
换换网络？

![Screenshot_20230323_145421.jpg](https://user-images.githubusercontent.com/20847533/227126447-eec7a76c-455a-4b85-be9e-fe2957e99e5a.jpg)

![Screenshot_20230323_145344.jpg](https://user-images.githubusercontent.com/20847533/227126466-3b6967f7-0131-4dba-82b1-9741d007f3e5.jpg)
