### ISSUE TITLE
在Readme中说明不发电的限制

### ISSUE THREAD

**Issue by seiren-naru-shirayuri** [niuhuan/pikapika#199]
如题，目前Readme中并未提及软件部分功能（如查看10页之后，跳页等）需要付费或参与小游戏才能解锁，希望在Readme中说明该限制。

**Comment by niuhuan** [comment]
这部分在releases里面有说明。

**Comment by niuhuan** [comment]
每个版本新增的功能都不同, 需要发电的功能, 只有在功能入口处有提示。

**Comment by niuhuan** [comment]
觉得软件不值得赞助可以去群里玩游戏一样可以用所有功能。并且这个仓库暂时不会对需要发电的功能解除限制。之前有很多人稍作修改就拿去卖。还请理解

**Comment by seiren-naru-shirayuri** [comment]
Release中只提及“如何发电”，但并未说明部分功能需要发电或小游戏来解锁。此外，个人认为“部分功能需要发电解锁”与“防止倒卖”有联系。您的软件是开源的，其他倒卖者照样可以自行修改去除限制再去倒卖。最后，我注意到您开通了爱发电，如果您肉身在国内的话可能会威胁到您的人身安全，可以考虑更换为国外赞助平台。

**Comment by niuhuan** [comment]
1.安全方面不需要担心，我使用邮箱和paypal登录爱发电。之前使用Patreon打赏，但是很多人反馈不方便。我并不希望软件分享到大陆或者其他禁止r18的国家。

2.现在的仓库gui是开源了，但缓存和数据库调度方面是闭源的（Native中部分，.a和.so）。暂时不用担心有人拿去改。

3.我很乐意分享技术，但是我讨厌别人用我的贡献去收割，不如自己收获打赏或者引导到自己群里。如果对软件有建议可以去群聊沟通。

**Comment by niuhuan** [comment]
我需要分开回答你的问题

1. 之前使用Patreon打赏但是多人反馈使用不便。并不需要担心安全，我用邮箱和PayPal登入Afdian。

2. 我的缓存和数据库调度是闭源的，它和gui是分离的，现在他人只可以打包操作界面。

3.我还是希望自己的commit的流量和收入流入自己交流社区而不是他人截获。发电部分多数都是附加功能，并不影响漫画的观看，所以没有列出来。限制页数很有必要，不然只改界面一样会被盗用。
