### ISSUE TITLE
windows端代理设置无效

### ISSUE THREAD

**Issue by xiaoning356** [niuhuan/pikapika#200]
Windows端的代理端口不论设置成什么，应用都走的1080端口 不走设置的端口

**Comment by niuhuan** [comment]
应用不受您全局代理的影响，走哪个端口取决于您在软件里面设置的URL。

**Comment by xiaoning356** [comment]
我设置的就是应用内的代理 我没有设置全局代理的习惯，不论是socks5://127.0.0.1/11111亦或是socks5://localhost/11111 都走的1080端口，不走代理软件开放的11111端口

**Comment by niuhuan** [comment]
您应该学习一下URL如何使用，

例如 http协议的默认端口是80，https是443，socks5则是1080。服务器地址与端口之间应该使用冒号（:）区分。

**Comment by xiaoning356** [comment]
好的，看岔了下面的示例，抱歉打扰了
