### ISSUE TITLE
多设备同步

### ISSUE THREAD

**Issue by BUGMojang** [niuhuan/pikapika#206]
刚用了几天，非常好用，然后我发现不能多设备之间同步阅读进度，也有可能是我没设置好
目前用的Android+Windows的端

**Comment by niuhuan** [comment]
Webdav是在启动的时候同步。

**Comment by niuhuan** [comment]
官方app在不同设备之间并不能同步记录。如果你手机获取root用户权限，可以把记录导入到我的应用里。

**Comment by BUGMojang** [comment]
感谢回复，用局域网搭建了wabdav，准备发电
好用！


niuhuan ***@***.***> 于2023年5月5日周五 17:39写道：
