### ISSUE TITLE
[android]怎么从1.6.6之前的版本迁移浏览记录到新版

### ISSUE THREAD

**Issue by gsgbullniu** [niuhuan/pikapika#208]
因为包名换了, 数据没法继承。 没找到导入导出浏览记录的办法，还有其他办法吗?
试了下直接覆盖 /data/data 下的数据, 导致新版闪退。

**Comment by niuhuan** [comment]
用webdav同步一下浏览记录

**Comment by gsgbullniu** [comment]
可是webdav功能好像是1.6.7之后才有的....

**Comment by gsgbullniu** [comment]
> 用webdav同步一下浏览记录

可是, webdav功能好像是1.6.7之后才有的....

**Comment by niuhuan** [comment]
软件崩溃是权限的原因吧？试试用sqlite同步一下view_log表？
