### ISSUE TITLE
希望增加可以复制评论的功能

### ISSUE THREAD

**Issue by pouring-rain** [niuhuan/pikapika#210]
刚才为了复制一个今佛曰，花了我二十分钟，这太可悲了。

**Comment by niuhuan** [comment]
可以考虑这个feature的加入，如果您没有关闭这个issue。


此外。您可以试一下ocr，就像QQ的截图识别。

**Comment by pouring-rain** [comment]
OCR 对于一般的评论复制还行，但对于日语的，以及加密的或者链接来说就不适用了
