### ISSUE TITLE
希望在每个漫画主页加个可以直接访问汉化组作品列表的点击项

### ISSUE THREAD

**Issue by pouring-rain** [niuhuan/pikapika#215]
大部分漫画他们都会把汉化组的名称用［］括起来的吧，或许可以加个这样的功能吗，正则拿出标题里汉化组的名称，然后加在作者名那个点击项的旁边。这样会挺方便用户搜索同一汉化组的作品，应该会增强不少用户体验。

**Comment by niuhuan** [comment]
汉化组和上传者在一行，都可以点击跳转

**Comment by pouring-rain** [comment]
> 汉化组和上传者在一行，都可以点击跳转

貌似我想叉了，我昨天是看着禁漫天堂然后提这个issue的，picacg貌似没有在标题写汉化组的习惯，禁漫天堂是有的。我该去jenny下重新提这个issue吗

**Comment by niuhuan** [comment]
您需要参考APP, 跟我的进行对比, 然后再提ISSUE。只有他们APP上有的我才能加, 与网页的协议是不一样的。

**Comment by pouring-rain** [comment]
> 您需要参考APP, 跟我的进行对比, 然后再提ISSUE。只有他们APP上有的我才能加, 与网页的协议是不一样的。

那应该是没有的，不过要做的话可以正则提出标题中的汉化组，然后调用搜索的接口吧

**Comment by niuhuan** [comment]
如果不是明确的字段, 我并不想做, 如果只是描述或者标题中的一部分。可以复制出来再搜索。

**Comment by pouring-rain** [comment]
是的，也不是刚需

**Comment by niuhuan** [comment]
或许可以加一个快速复制或者搜索的功能 根据中括号匹配, 可以在jm的仓库里提一下, 不知道什么时候会做

**Comment by pouring-rain** [comment]
> 或许可以加一个快速复制或者搜索的功能 根据中括号匹配, 可以在jm的仓库里提一下, 不知道什么时候会做

好的，大佬加油

**Comment by niuhuan** [comment]
是的，最近没有维护了

**Comment by 1433020484** [comment]
那以后还有可能更新吗
