### ISSUE TITLE
【需求】下载时将漫画打包成.cbz格式

### ISSUE THREAD

**Issue by TenmaSennpai** [niuhuan/pikapika#216]
加入一个选项，可以在“下载的同时导出到文件系统”的同时将漫画的每一话打包成.cbz格式，形成以下的文件结构
![image](https://github.com/niuhuan/pikapika/assets/64529818/71623a81-e19b-4105-be20-b689dd9042f1)
其中，.cbz压缩包中没有文件夹结构
![image](https://github.com/niuhuan/pikapika/assets/64529818/999c0414-1201-45ce-8bf2-a89433ea2413)

**Comment by niuhuan** [comment]
可以！我觉得是个很不错的功能。需要耐心等待，开发周期并不确定。

**Comment by niuhuan** [comment]
已经开发完成并构建，导入功能如果需要以后再弄。

https://github.com/niuhuan/pikapika/actions/runs/5502828486/jobs/10027581500

https://github.com/niuhuan/pikapika/releases/tag/v1.7.6
