### ISSUE TITLE
注册时显示PlatformException( validation error，，null)

### ISSUE THREAD

**Issue by 1596944197** [niuhuan/pikapika#218]
![a349e4a2b2d20d833a5fafe4003b8fc](https://github.com/niuhuan/pikapika/assets/68650762/705e57c9-cf3d-4ba3-901f-5f70eb51d93f)

**Comment by niuhuan** [comment]
校验不通过， 账号密码都用英文+数字组合试试

**Comment by 1596944197** [comment]
> 校验不通过， 账号密码都用英文+数字组合试试

可以了，谢谢你！好心人
