### ISSUE TITLE
不知道是不是bug

### ISSUE THREAD

**Issue by 1815690862** [niuhuan/pikapika#222]
![Screenshot_20230817_112036.jpg](https://github.com/niuhuan/pikapika/assets/78188209/73acdba4-6264-48ba-8bfa-9a70070cdc99)

这个按钮点不到，其他功能正常

**Comment by niuhuan** [comment]
有没有可能，是我没开发完

**Comment by 1815690862** [comment]
> 有没有可能，是我没开发完

哈哈哈😂，不好意思

**Comment by niuhuan** [comment]
对不起，这个APP没什么人支持，有点太监了

**Comment by 1815690862** [comment]
> 对不起，这个APP没什么人支持，有点太监了 

喜欢二次元的，估计很少逛这种网站（GitHub）
- [ ] 可能需要推广，宣传宣传

**Comment by niuhuan** [comment]
不需要宣传，我只要星星就可以了。宣传不会带来好处，说不定还有危险。
