### ISSUE TITLE
希望能够在搜索的时候添加向下滚动自动翻页的功能

### ISSUE THREAD

**Issue by Minori-ty** [niuhuan/pikapika#232]

**Comment by niuhuan** [comment]
细说一下, 不然我还没听懂

**Comment by Minori-ty** [comment]
> 细说一下, 不然我还没听懂

就是在搜索内容的时候，jenny滚动可以自动加载下一页。而pika要手动点击下一页

**Comment by niuhuan** [comment]
据我记忆, 设置里面能选翻页器还是滚动, 所有的翻页用的统一逻辑。

**Comment by Minori-ty** [comment]
> 据我记忆, 设置里面能选翻页器还是滚动, 所有的翻页用的统一逻辑。

好的看到了，原来是在设置里面，弄得很隐蔽。我还以为是直接在搜索栏上方选择，找半天没找到
