### ISSUE TITLE
platformexception(error,unauthorized,null,null)

### ISSUE THREAD

**Issue by ziwangqi** [niuhuan/pikapika#237]
win10-64位系统，挂了ssr登录成功之后无法刷新出信息。报错内容如图所示。
![1](https://github.com/niuhuan/pikapika/assets/75244300/f32c3d5e-a81b-43c0-8ae9-703e8aa2ed93)
![2](https://github.com/niuhuan/pikapika/assets/75244300/717f18c0-ce4d-4848-944f-6c2932546708)
![3](https://github.com/niuhuan/pikapika/assets/75244300/ae136d51-ef86-4e3f-88c8-9d863edd547f)

**Comment by niuhuan** [comment]
退出重新登录一下

**Comment by ziwangqi** [comment]
感谢作者的迅速回复！我尝试登出并重新登录，这次我把自己的ssr关闭，情况照旧，如图片4-7所示。另附我的机器设备信息图8和所使用的的pika版本信息图9供您确认问题


風船を恐れて
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "niuhuan/pikapika"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月9日(星期四) 下午4:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [niuhuan/pikapika] platformexception(error,unauthorized,null,null) (Issue #237)





 
退出重新登录一下

**Comment by niuhuan** [comment]
unauthorized 本身就是Token失效或者账号密码不对的意思, 可以证明网络是没有问题的。
我刚才在手机上安装了最新版可以正常使用。还需要你尝试。或者使用手机版。

**Comment by ziwangqi** [comment]
感谢您的耐心解答，我先尝试重新注册账号并登录或者找回密码试试看



---Original---
From: ***@***.***&gt;
Date: Thu, Nov 9, 2023 17:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [niuhuan/pikapika]platformexception(error,unauthorized,null,null) (Issue #237)




 
unauthorized 本身就是Token失效或者账号密码不对的意思, 可以证明网络是没有问题的。
 我刚才在手机上安装了最新版可以正常使用。还需要你尝试。或者使用手机版。
