### ISSUE TITLE
安卓怎么找安装包

### ISSUE THREAD

**Issue by link200145** [niuhuan/pikapika#238]
不会下载啊

**Comment by niuhuan** [comment]
https://github.com/niuhuan/pikapika/issues/214

**Comment by link200145** [comment]
> [第214章](https://github.com/niuhuan/pikapika/issues/214)哪个是apk啊，没找到，安装教程没看懂

**Comment by niuhuan** [comment]
手动输入releases地址, 仓库URL/releases/ 就是了
