### ISSUE TITLE
JM发电

### ISSUE THREAD

**Issue by CHYYDSCH** [niuhuan/pikapika#245]
能不能把JM的发电去掉，之前下载了好多，后来APP删除了现在无法登录。
没登录就不能发电，不能发电就不能导入。
因为电脑上登录后没删掉，现在虽然不能看，但是因为发过电，所以是能导入的
麻烦把JM改个不用登录版本，去掉发电，只要能导入功能

**Comment by niuhuan** [comment]
您导出的是zip还是jmi？

**Comment by CHYYDSCH** [comment]
好的，我试试



niuhuan ***@***.***> 于 2023年12月4日周一 下午4:52写道：
