### ISSUE TITLE
能不能解绑哔咔和发电账号

### ISSUE THREAD

**Issue by safauaia** [niuhuan/pikapika#260]
我的telegram账号前段时间被封了，现在用的新的账号，新账号和哔咔账号绑定了但是不能发电，请问有什么能解决的办法吗

**Comment by niuhuan** [comment]
重新绑定一下

**Comment by safauaia** [comment]
绑定没错，发电之后弹窗也是显示success，但是还是用不了发电之后的功能
![Screenshot_20240212_230013](https://github.com/niuhuan/pikapika/assets/149290704/32f80fce-26a9-423f-92e4-742c0153b838)

**Comment by niuhuan** [comment]
用登录名、不能带符号 从tg群里问一下
