### ISSUE TITLE
4月11日时无法登陆

### ISSUE THREAD

**Issue by zihaojialidun** [niuhuan/pikapika#271]
显示Connect:no route to host

**Comment by zihaojialidun** [comment]
登陆可以正常登陆picacg

**Comment by zihaojialidun** [comment]
![Screenshot_20240411_225050_opensource pikapika](https://github.com/niuhuan/pikapika/assets/141239326/3c1f6eb0-49b1-4a99-9364-4055cacf9f1f)
账号及密码正确，也没有使用魔法

**Comment by niuhuan** [comment]
换个分流或使用魔法，这几天会更新一下分流2/3。
