### ISSUE TITLE
webdav同步时报错

### ISSUE THREAD

**Issue by Earmo** [niuhuan/pikapika#279]
软件版本：v1.7.9
系统版本：安卓11

使用同步功能时报错
 `PlatformException(,disk 1/O error:read-only file system,null)`
坚果云和群晖webdav都是报这个

![IMG_20240424_004255](https://github.com/niuhuan/pikapika/assets/42935502/2ad46199-568f-4add-9e40-db20a730ba47)
![IMG_20240424_004323](https://github.com/niuhuan/pikapika/assets/42935502/a26b4dd6-5687-425b-ba98-7259eeb30bb5)

**Comment by niuhuan** [comment]
可以加群问一下群友怎么配的、也许程序确实有问题

**Comment by niuhuan** [comment]
不知道之前的版本是否有问题

**Comment by zacader** [comment]
坚果云同步错误
