### ISSUE TITLE
更新后进不去

### ISSUE THREAD

**Issue by hyyx233** [niuhuan/pikapika#280]
从1.7.8更新到1.7.9之后一直卡在皮卡丘那个画面不动，这是什么问题，pc版能进去但是安卓版用模拟器试了一下178能正常进179就进不去，因为手机上的下载数据还没法卸载重新装178

**Comment by niuhuan** [comment]
或许应该升级您的安卓系统版本，再或者使用较低版本的flutter 2.x 引擎 。目前使用安卓API-Q测起来使用并无问题

**Comment by lhj5426** [comment]
![Screenshot_20240503_215119_idm internet download manager plus](https://github.com/niuhuan/pikapika/assets/30548000/cdd7a93d-e9af-47c2-8820-db1c425d92b5)
我也遇到了卡皮卡丘的问题

**Comment by specked2527** [comment]
> 或许应该升级您的安卓系统版本，再或者使用较低版本的flutter 2.x 引擎 。目前使用安卓API-Q测起来使用并无问题
 安卓9 卡在开屏界面 只能降级使用1.78
pikapika-v1.7.9_flutter-2.10.5-android-arm64.apk

**Comment by VillagerTom** [comment]
似乎是golang后端的问题，logcat一直在输出
```
E Go      : 没有找到要下载的漫画
E GoLog   : 没有找到要下载的漫画
```

**Comment by niuhuan** [comment]
这个日志，是后台下载进程，不断轮训任务输出的，一直卡在皮卡丘是在进行登录。网络被阻塞，也没有返回，超时时间很久。

> 似乎是golang后端的问题，logcat一直在输出
> 
> ```
> E Go      : 没有找到要下载的漫画
> E GoLog   : 没有找到要下载的漫画
> ```
