### ISSUE TITLE
图片分流莫名炸了

### ISSUE THREAD

**Issue by cocoxqy** [niuhuan/pikapika#281]
图片分流全部显示失败，不管是WiFi还是流量都不管用，内容能点进去就是图片一直没法显示
![Screenshot_20240510_222659](https://github.com/niuhuan/pikapika/assets/167335382/194b3103-9260-4189-9cc7-f9d39c90d2a0)
![Screenshot_20240510_223309](https://github.com/niuhuan/pikapika/assets/167335382/43d86438-36c9-4fc9-b24a-d21f3dbcee4b)

**Comment by niuhuan** [comment]
无解了，试试开代理
