### ISSUE TITLE
x509？证书？无法登录

### ISSUE THREAD

**Issue by pthc6yo** [niuhuan/pikapika#282]
看了很多博客文章，好像是安卓系统里的证书出了问题。下一步不知道怎么搞了，求救

![S40527-06004241](https://github.com/niuhuan/pikapika/assets/96957559/ee5ca179-39b7-46c6-a7f5-1e49eeaeaa09)
![S40527-06005751](https://github.com/niuhuan/pikapika/assets/96957559/e1b34e0a-0b2c-4e57-9d79-b995ccbc3a99)

**Comment by niuhuan** [comment]
设备太老了 (˵¯͒〰¯͒˵)

**Comment by niuhuan** [comment]
或设备时间不挣钱
