### ISSUE TITLE
电脑导出下载内容时出现问题

### ISSUE THREAD

**Issue by fdjgw8u** [niuhuan/pikapika#290]
有些漫画的标题会出现windows的非法字符，比如 “；”  “：”  “/”  等，会导致导出失败，也会导致批量导出中断。实际上这类标题并不少见，希望可以在导出前将该类字符自动替换为下划线，从而可以正常导出

**Comment by niuhuan** [comment]
十分感谢您的issue， “/”已经存在于特殊符号数组中，导出时进行替换为下划线。我将追加英文分号“；”，英文冒号“:”为特殊字符。并在近期进行发布。

您可以使用导出前重命名暂时跳过此错误。
