### ISSUE TITLE
没法关联到软件

### ISSUE THREAD

**Issue by 2069168265** [niuhuan/pikapika#291]

**Comment by niuhuan** [comment]
您的图片没有上传成功

您可以来群里询问一下群友，很乐意给您解答


https://t.me/+7EyAiARvtENkMTU1

**Comment by 2069168265** [comment]
> 您的图片没有上传成功
> 
> 您可以来群里询问一下群友，很乐意给您解答
> 
> https://t.me/+7EyAiARvtENkMTU1

算了TAP那20算我赞助了
我在爱发电又发电了一次

**Comment by niuhuan** [comment]
首先要感谢您对个人开发者的鼓励。

如果是 PAT，是订阅制，您可以尽快去取消会员或改为免费会员。我并不知道patreon的退款制度，（是否当天退会可退款）。

1. 我并不希望多扣您的费用，可以加群私聊我， 给您延长发电时间。
2. PAT以及支援服务器均在大陆内无法访问, 需要手机需要使用全局的代理， 或将亚马逊aws，以及patron的网址加入代理策略才可以访问。
3.

**Comment by 2069168265** [comment]
> 首先要感谢您对个人开发者的鼓励。
> 
> 如果是 PAT，是订阅制，您可以尽快去取消会员或改为免费会员。我并不知道patreon的退款制度，（是否当天退会可退款）。
> 
> 1. 我并不希望多扣您的费用，可以加群私聊我， 给您延长发电时间。
> 2. PAT以及支援服务器均在大陆内无法访问， 需要手机需要使用全局的代理， 或将亚马逊aws，以及patron的网址加入代理策略才可以访问。

没关系

**Comment by niuhuan** [comment]
![bb450b348ef6aa90afce64445c67befe](https://github.com/user-attachments/assets/e7ef9cf2-bc88-4c32-98ef-d299c8b1ea2e)
