### ISSUE TITLE
flutter_styled_toast >=2.0.0 requires intl   0.19.0.

### ISSUE THREAD

**Issue by 903612643** [niuhuan/pikapika#296]
yangdeyuan@yangdeyuandeMacBook-Pro ios % flutter pub get
Resolving dependencies in `/Users/yangdeyuan/Downloads/pikapika-master`... (3.1s)
Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because flutter_styled_toast >=2.0.0 depends on flutter_localizations from sdk
  which depends on intl 0.19.0, flutter_styled_toast >=2.0.0 requires intl
  0.19.0.
So, because pikapika depends on both flutter_styled_toast ^2.0.0 and intl
  ^0.17.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Try upgrading your constraint on intl: flutter pub add intl:^0.19.0
yangdeyuan@yangdeyuandeMacBook-Pro ios %

**Comment by 903612643** [comment]
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  isolate: ^2.1.1
  event: ^2.0.5
  flutter_search_bar: ^3.0.0-dev.1
  flutter_svg: ^1.0.3
  flutter_styled_toast: ^2.0.0
  another_xlider: ^1.0.1+2
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  permission_handler: ^10.1.0
  url_launcher: ^6.0.9
  clipboard: ^0.1.3
  photo_view: ^0.13.0
  multi_select_flutter: ^4.0.0
  flutter_datetime_picker: ^1.5.1
  modal_bottom_sheet: ^3.0.0-pre
  image_cropper: ^1.5.0
  image_picker: ^0.8.6
  file_picker: ^5.2.1
  crop_image: ^1.0.2
  image: ^3.1.3
  path: ^1.8.0
  uri_to_file: ^0.2.0
  uni_links: ^0.5.1
  filesystem_picker: ^3.0.0-beta.1
  intl: ^0.19.0

**Comment by niuhuan** [comment]
使用较低版本的flutter(3.7.3
不要修改yaml中的依赖依赖版本

代码部分需要同事兼容flutter2/3
