### ISSUE TITLE
关于软件界面的一些建议

### ISSUE THREAD

**Issue by zhongfly** [niuhuan/pikapika#3]
- [x] 1，显示上传者，点击可以查看其上传的所有漫画(有的是某汉化组上传，还是有意义)，我觉得可以放在时间一栏的左侧
- [x] 2，在漫画列表和漫画详情页显示漫画页数，总页数或每话页数。
- [x] 3，漫画列表里滑动至页底时，自动加载下一页，而不是目前这种翻页式的操作
- [x] 4，漫画阅读页面：参考目前大多数漫画应用的操作，点击界面中间显示设置(进度滑动条)，使得可以完全无遮挡的全屏，设置中添加修改图片质量等快捷设置
- [x] 5，漫画阅读页面：进度条直接显示总页数与当前所在页数，而非滑动时才显示当前所在页数
- [x] 6，关于页面中显示软件版本号
- [x] 7，可以屏蔽某些tag，不显示有对应tag的漫画
- [x] 8，登录失败应有提示，比如弹窗，目前的体验类似点了保存没反应一样。
- [x] 9，加载失败的图片可以重新加载
- [x] 10，评论显示时间
- [x]  11，软件主页“浏览”里，可以不显示某些分类
- [x]  12，更改排序后立刻刷新重载该分类

**Comment by zhongfly** [comment]
”我的“页面中的”关于“用五角星标识是不是没那么直观？一般五角星是被用于表示收藏功能的，我建议换成”i“
参考：
![about](https://image.flaticon.com/icons/png/512/151/151776.png)

**Comment by niuhuan** [comment]
3。 每次阅读漫画已经加载了所有的图片。不需要再翻页了。只有一个下一章的按钮。

**Comment by zhongfly** [comment]
> 3。 每次阅读漫画已经加载了所有的图片。不需要再翻页了。只有一个下一章的按钮。

说的是漫画列表那里…就是例如某分区或则搜索后的页面，很多个漫画

**Comment by niuhuan** [comment]
如果页数多的话, 下拉加载更多体验并不会很好,

**Comment by zhongfly** [comment]
6，关于页面中显示软件版本号

**Comment by zhongfly** [comment]
7，可以屏蔽某些tag，不显示有对应tag的漫画

**Comment by zhongfly** [comment]
8，登录失败应有提示，比如弹窗，目前的体验类似点了保存没反应一样。

**Comment by zhongfly** [comment]
9，加载失败的图片可以重新加载

**Comment by zhongfly** [comment]
> 如果页数多的话, 下拉加载更多体验并不会很好,

改成到底后，往上拖动就翻页，用这样的手势应该会更好。纯靠点击”下一页“不太方便

**Comment by niuhuan** [comment]
单击屏幕全屏无遮挡, 需要在设置一下才能用

**Comment by niuhuan** [comment]
> > 如果页数多的话, 下拉加载更多体验并不会很好,
> 
> 改成到底后，往上拖动就翻页，用这样的手势应该会更好。纯靠点击”下一页“不太方便

我想设计成跟下拉刷新一样, 拉动到一定长度松手就能上一页,下一页, 还在找解决方案。

**Comment by zhongfly** [comment]
> > > 如果页数多的话, 下拉加载更多体验并不会很好,
> > 
> > 
> > 改成到底后，往上拖动就翻页，用这样的手势应该会更好。纯靠点击”下一页“不太方便
> 
> 我想设计成跟下拉刷新一样, 拉动到一定长度松手就能上一页,下一页, 还在找解决方案。

不过还是期望像瀑布流那样，可以无限下滑，滑到最底下就开始加载下一页……可能有难度吧

**Comment by niuhuan** [comment]
3 , 5 , 8 都完成了, 自己build一下, 然后在设置里改成瀑布流用吧

**Comment by niuhuan** [comment]
7 里面的tag是不能屏蔽的, pika屏蔽的是分类, 我做了一样的效果

**Comment by zhongfly** [comment]
> 7 里面的tag是不能屏蔽的, pika屏蔽的是分类, 我做了一样的效果

有些分类不应该加入被屏蔽的，例如大家都在看、牛牛不哭、那年今天、官方都在看…
另外，在列表里“被封印的本子”项目能不能小一点，别占用太多高度

**Comment by niuhuan** [comment]
11和7做成一个 还是单独一个设置比较好。

**Comment by zhongfly** [comment]
> 11和7做成一个 还是单独一个设置比较好。

分开吧

**Comment by niuhuan** [comment]
“被封印的本子” 体积调小了一点, 卡片边框去掉了, 美观了一些, 首页分类屏蔽一些分类的功能加上了。

**Comment by zhongfly** [comment]
> 11和7做成一个 还是单独一个设置比较好。

被屏蔽的分类标签在首页分类里也会被屏蔽来着……这么看来要不设置合并，要不就改成首页进入该分类时不屏蔽当前分类的标签

**Comment by niuhuan** [comment]
这样搞就很复杂, 还是合并成一个比较好

**Comment by niuhuan** [comment]
7与11, 合成并成一个了，版本号这个我不想每次都改，想每次构建的时候把打包时间放里面。

**Comment by niuhuan** [comment]
12刷新了啊，我刚试的

**Comment by niuhuan** [comment]
> 12刷新了啊，我刚试的

瀑布的没有刷新?

**Comment by zhongfly** [comment]
> 7与11, 合成并成一个了，版本号这个我不想每次都改，想每次构建的时候把打包时间放里面。

版本号还是很重要的，每次发布新版本的时候改一下吧…

**Comment by zhongfly** [comment]
”加载失败的图片可以重新加载“
这个实现了吗？当加载失败显示为X时，有办法手动刷新加载吗？
不如不显示为X，而是一个重试的按钮，并且增加加载的动画
