### ISSUE TITLE
状态栏问题

### ISSUE THREAD

**Issue by zxc173123** [niuhuan/pikapika#308]
左图，状态栏颜色覆盖层能不能去掉
右图，更换主题颜色状态栏颜色就同步了但是重启又有覆盖层
安卓14，澎湃1.0
![img_20241123_202242](https://github.com/user-attachments/assets/ad9c59be-60d8-485a-a388-4a6fdeebc1e8)

**Comment by niuhuan** [comment]
感谢您的反馈，系统兼容性的问题修复起来会很漫长。
