### ISSUE TITLE
iOS端搜索无法使用

### ISSUE THREAD

**Issue by wwalt1a** [niuhuan/pikapika#312]
尝试切换多个代理节点均报错：
![IMG_0866](https://github.com/user-attachments/assets/e8eb2fab-cb66-46a1-bdb6-3224d3fc2c1f)

主页右上角的搜索按钮搜索内容报上图错误，在作品页面点击作者名字也报错，但是点击tag可以正常搜索tag
使用版本[pikapika-v1.8.4_flutter-3.7.3-ios-nosign.ipa](https://github.com/niuhuan/pikapika/releases/download/v1.8.4/pikapika-v1.8.4_flutter-3.7.3-ios-nosign.ipa)

**Comment by niuhuan** [comment]
出现两个横线加逗号，应该服务器报错了，某卡服务器故障的时候经常这样，您可以贴一下搜索的内容，应该大概率解决不了，可以尝试一下官方安卓客户端是不是报错

**Comment by wwalt1a** [comment]
> 出现两个横线加逗号，应该服务器报错了，某卡服务器故障的时候经常这样，您可以贴一下搜索的内容，应该大概率解决不了，可以尝试一下官方安卓客户端是不是报错

恢复正常了，还真是你说的服务器问题
