### ISSUE TITLE
[建议] 若干建议

### ISSUE THREAD

**Issue by HiRA017** [niuhuan/pikapika#32]
1. 添加支持“预加载”特性，使阅读体验更流畅
> 预加载接下来2张图片的内容，有效减少阅读时加载图片的等待时间

2. 希望将加载新图片时的占位用图片删去，用普通的加载动画代替（转圈圆环）

3. 如果可以的话，添加支持Android 10或更新版本下，跟随系统切换深色主题

**Comment by niuhuan** [comment]
1. 预加载是有的, 和手机的可视区有关系
2. 加载动画因人而异, 并不是每个人都喜欢
3. 已经在最新的release中得到了支持

**Comment by Z-fly** [comment]
2. 那你就在设置里提供选项，让用户自己选择是否使用加载动画

**Comment by HiRA017** [comment]
> 1. 预加载是有的, 和手机的可视区有关系
> 2. 加载动画因人而异, 并不是每个人都喜欢
> 3. 已经在最新的release中得到了支持

谢谢回应！(ㆁωㆁ)

**Comment by Z-fly** [comment]
其实我是在回niuhuan，虽然我不是它的产品经理

**Comment by niuhuan** [comment]
> 其实我是在回niuhuan，虽然我不是它的产品经理

2的实现并不难，🤣 我只是觉得加载那个小圆球一直在转没有水印体验好，而且这种设置太细微了。

![Screenshot_20210929-011133](https://user-images.githubusercontent.com/20847533/135134015-a969e9a6-140c-4ee8-b1e9-4aad492d4dc8.jpg)

**Comment by HiRA017** [comment]
> > 其实我是在回niuhuan，虽然我不是它的产品经理
> 
> 2的实现并不难，🤣 我只是觉得加载那个小圆球一直在转没有水印体验好，而且这种设置太细微了。
> 
> webtoon模式有预加载，相册模式好像没有。

啊，这个在列表里当然是静态水印好啦！我是指相册模式里载入下一张图时候的那个水印啦，就突然一大块，冲劲瞬间被截住🥲 换成转圈圈动效或者稍微不那么突兀的水印兴许会好一点。当然这也仅仅是个人非常主观的愚见，如果会很麻烦的话那就不劳另外费神啦！

十分感谢你开发的软件，能让咱们冲得更flutter一点🤪

**Comment by niuhuan** [comment]
> > > 其实我是在回niuhuan，虽然我不是它的产品经理
> > 
> > 
> > 2的实现并不难，🤣 我只是觉得加载那个小圆球一直在转没有水印体验好，而且这种设置太细微了。
> > webtoon模式有预加载，相册模式好像没有。
> 
> 啊，这个在列表里当然是静态水印好啦！我是指相册模式里载入下一张图时候的那个水印啦，就突然一大块，冲劲瞬间被截住🥲 ![Screenshot_20210929-024717](https://user-images.githubusercontent.com/91152901/135147590-19ed98fb-cf90-4e18-8519-f10d8f99102f.png)
> 
> 换成转圈圈动效或者稍微不那么突兀的水印兴许会好一点。当然这也仅仅是个人非常主观的愚见，如果会很麻烦的话那就不劳另外费神啦！
> 
> 十分感谢你开发的软件，能让咱们冲得更flutter一点🤪

相册模式用的photo＿view， 把水印调成一半大小应该可以，还不熟练这个插件，看看怎么预加载。

**Comment by niuhuan** [comment]
@HiRA017 
新版如果网速够快，不会有那个黑色加载动画了。

**Comment by HiRA017** [comment]
好耶！（其实昨晚已经第一时间更新啦🥳辛苦啦
