### ISSUE TITLE
窗口初始化还是不行呀

### ISSUE THREAD

**Issue by Z-fly** [niuhuan/pikapika#42]
https://user-images.githubusercontent.com/10470892/137621662-aa5c4cb0-86e2-4de3-bff9-ada0d49bbfea.mov

我每次都得调
所以说一直在讲的自适应，不知道是不是Flutter实现不了 还是你代码实现不了

**Comment by niuhuan** [comment]
获取显示器大小并且在显示器内，这个比较麻烦，我只能得到一个glfx的窗口，还要去看看glfx的api

**Comment by Z-fly** [comment]
你可以加我：2658041579

**Comment by niuhuan** [comment]
现在能记住全屏了
