### ISSUE TITLE
关于自动更新以及版本号

### ISSUE THREAD

**Issue by niuhuan** [niuhuan/pikapika#45]
我希望这个版本

我期望将版本号将放到 /lib/assets 里
{
nightyVersion: "",
stableVersion: "",
content: '',
}

启动程序的时候进行校验 读取仓库的本地的版本进行校验, 如果更高则提示更新。
我期望更友好一点，考虑到手机和电脑都能使用。

或者有没有办法读取releases

@zhongfly
@Z-fly

**Comment by zhongfly** [comment]
github rest api 
https://docs.github.com/en/rest/reference/repos#get-the-latest-release

**Comment by Z-fly** [comment]
如果站在产品经理的角度看，应该是尽量满足大众的需求，哔咔本身不挂代理也能看，

**Comment by zhongfly** [comment]
> 如果站在产品经理的角度看，应该是尽量满足大众的需求，哔咔本身不挂代理也能看(换句话说大部分人也没有代理)，通过代理地址更新软件也没有增加开发难度

你给出的网站并不能反代github的rest api，只是文件的反代罢了

**Comment by Z-fly** [comment]
那你有什么好办法吗？

**Comment by zhongfly** [comment]
> 那你有什么好办法吗？

本来这个项目就一直只在github分发，若是要简单的获取版本信息（本issue的重点也只是如何获取版本号，不涉及分发），配合release分发的情况下使用github的api是最佳选择之一，获取到是跟随release版本号实时变化的。

次一级的方法是手动添加一个版本信息文件在仓库中，检查更新时下载它、读取，但问题在于需要每次都手动更新版本号，十分麻烦。
次一级的自动化方法是考虑利用github action，在每次版本发布时（github action可被tag或者commit触发），更新仓库中的版本信息文件。

综上，最简单的方法的确就是我之前提出通过github rest api获取版本信息最简单，最省事。
