### ISSUE TITLE
本子更新时间优化

### ISSUE THREAD

**Issue by Z-fly** [niuhuan/pikapika#53]
当前只显示日期
增加显示更新时间

**Comment by niuhuan** [comment]
本来缓存就有两个小时或更久, 有必要精确到小时么?

**Comment by Z-fly** [comment]
> 本来缓存就有两个小时或更久, 有必要精确到小时么?

不是显示缓存时间，你看官方app每个本子都有发布时间点

**Comment by niuhuan** [comment]
当初是觉得太难看了, 显示的太长, 1080的手机上看着不是很美观, 所以只保留了日期
