### ISSUE TITLE
v1.1.x 与 v1.2.x 文件迁移说明

### ISSUE THREAD

**Issue by niuhuan** [niuhuan/pikapika#56]
应用程序已经重新命名为 pikapika (源自一种啮齿类动物的叫声, 并没有实际意义)。

如果您以前曾下载过 v1.1.x 或更早的 v1.0.x 的 release。之后更新为v1.2.x, 且希望前后版本数据兼容, 您可以参考这个issue。

Windows :  
  - ${程序文件夹}/data/pikapi/* => ${程序文件夹}/pikapi/*
  -  您可以将pikapi内文件移动或覆盖到data, 最后删除pikapi文件夹。

MacOS
  - "\~/Library/ApplicationSupport/pikapi" => "\~/Library/ApplicationSupport/pikapika"
  - 关闭软件并迁移覆盖文件

Linux
  - "\~/.pikapi" => "\~/.pikapika"
  - 关闭软件并迁移覆盖文件

iOS
  - 不同APP副本的形式存在, 即使数据一摸一样
  - 未取得最高权限(越狱)将不能进行迁移

Android
  - 不同APP副本的形式存在, 即使数据一摸一样
  - 可以使用APP内的迁移功能, 反复迁移 (新旧版本都进行迁移, 然后使用文件管理器覆盖文件, 再删除旧版本)
  - 获取ROOT权限的话, 覆盖 /data/data/niuhuan.pikapi => /data/data/niuhuan.pikapika

**Comment by zhongfly** [comment]
安卓的包名没变，依旧是覆盖更新
https://github.com/niuhuan/pikapika/blob/master/android/app/build.gradle#L37

**Comment by niuhuan** [comment]
> 安卓的包名没变，依旧是覆盖更新 https://github.com/niuhuan/pikapika/blob/master/android/app/build.gradle#L37

现在变了 (滑稽)

**Comment by niuhuan** [comment]
构建脚本启动在的时候, 会输入一个版本号, 被存入 lib/assets/version.txt

软件启动的时候去 https://api.github.com/repos/niuhuan/pikapika/releases/latest 拉取一下最新的versionName.,跟本地的比一下, 不一样就是有新版本.

如果没有versionName就会认为是dirty版本, 开发中构建的版本, 不检查更新.

**Comment by zhongfly** [comment]
> > 安卓的包名没变，依旧是覆盖更新 https://github.com/niuhuan/pikapika/blob/master/android/app/build.gradle#L37
> 
> 现在变了 (滑稽)

用了你发布的最新版，包名没变，不需要迁移

**Comment by zhongfly** [comment]
迁移功能有问题，等于导出功能，但是没有导入…

**Comment by niuhuan** [comment]
> 迁移功能有问题，等于导出功能，但是没有导入… 正常的来说，应该是自定义导出到xx文件夹，自定义从xx文件夹导入

那个会彻底更改数据库的保存位置，下次启动会从迁移到的位置读取，一开始是为了解决某些用户希望使用内存卡保存缓存和数据的问题

新旧都迁移到非/data的位置，之后用x-plore或其他的文件管理工具，复制或移动覆盖旧的版本资料到新的，这样就完成新旧版本数据迁移。

这时候可以选择继续使用，或者迁移回/data（没有实际意义）
