### ISSUE TITLE
【macOS】遇到闪退可能的解决方法

### ISSUE THREAD

**Issue by Z-fly** [niuhuan/pikapika#57]
![](https://user-images.githubusercontent.com/10470892/141390697-bddfd10f-7b6e-459a-9053-a537c952df59.png)
在输入监听那里重新取消打钩，然后再次打钩，就不闪退了

**Comment by niuhuan** [comment]
你打开就闪退么
我白苹果, 黑苹果都没有问题

**Comment by niuhuan** [comment]
![WX20211112-095734](https://user-images.githubusercontent.com/20847533/141395797-464800ee-84e3-4a2e-bf83-dfdab4124d8a.png)

mac11.6
