### ISSUE TITLE
关于分流功能的疑问

### ISSUE THREAD

**Issue by zhongfly** [niuhuan/pikapika#58]
我看了一下别的客户端，发现分流都是通过修改请求头里的app-channel项实现的，这个应用却是写死了ip地址？
从我个人理解看，不应该是前者更简单并且更容易适应分流地址的变化吗？

**Comment by zhongfly** [comment]
分流1 2 3对应的就是请求头里的app-channel=1 2 3

**Comment by niuhuan** [comment]
> 分流1 2 3对应的就是请求头里的app-channel=1 2 3

我觉得那个header/channel只是是给服务器用的。

毕竟再怎么换header也解决不了网速和网络的的问题。

这几个ip是在官方app更换分流后，抓包抓到的。

**Comment by zhongfly** [comment]
> > 分流1 2 3对应的就是请求头里的app-channel=1 2 3
> 
> 我觉得那个header/channel只是是给服务器用的。
> 
> 毕竟再怎么换header也解决不了网速和网络的的问题。
> 
> 这几个ip是在官方app更换分流后，抓包抓到的。

我认为是是有效果的，反而是直接用ip的情况下，我经常出现图片无法显示的问题(有代理的情况下)。

**Comment by zhongfly** [comment]
不过我又抓包研究了图片地址，发现不同分流是对应不同图片域名，
例如
分流1 https://storage.wikawika.xyz/static/d02d3540-2a40-4de3-b248-609b751e5244.jpg
分流2 https://s3.picacomic.com/static/d02d3540-2a40-4de3-b248-609b751e5244.jpg
分流3 https://s3.picacomic.com/static/d02d3540-2a40-4de3-b248-609b751e5244.jpg

**Comment by zhongfly** [comment]
请求头上的app-channel的确没用，返回的图片地址是固定的，全靠客户端自己更换图片域名

**Comment by niuhuan** [comment]
我在下载图片的时候，我并没有换域名，而是分别请求了不同的分流地址。只换域名用原网络请求一样被墙或很慢。
