### ISSUE TITLE
导入仅显示storage文件夹没有下级目录

### ISSUE THREAD

**Issue by Jacheers** [niuhuan/pikapika#61]
![Screenshot_2021-11-17-20-58-26-203_niuhuan.pikapika.jpg](https://user-images.githubusercontent.com/61894695/142205075-d4e6d01d-7bff-48f9-b744-f0d233e7d283.jpg)

**Comment by niuhuan** [comment]
1

**Comment by Jacheers** [comment]
@niuhuan 确实加了权限就行了。
