### ISSUE TITLE
手机APP无法注册

### ISSUE THREAD

**Issue by Alicerong** [niuhuan/pikapika#62]

**Comment by Alicerong** [comment]
国内三网均尝试过，魔法上网也不行。

**Comment by niuhuan** [comment]
> 国内三网均尝试过，魔法上网也不行。

- 如果你有某卡账号, 直接登录即可, 理论上一样的网络环境就可以。
- 我希望能知道您提示错误显示的是什么?
- 注册的时候, 您只需要随便填写一下账号密码, 需要是英文。

**Comment by Alicerong** [comment]
该换某卡ID后可以成功登陆了。

**Comment by Alicerong** [comment]
谢谢
