### ISSUE TITLE
安卓9，启动1.2.2版本软件报错

### ISSUE THREAD

**Issue by 546649816** [niuhuan/pikapika#63]
用了vpn和不用都报错
PlatformException(, Post

"https://***.com/auth/register": dial tcp

199.96.63.177:443: i/o timeout,,nul)

**Comment by niuhuan** [comment]
i/o timeout , 说明链接到了服务器, 但是网络过慢, 您可以试试切换分流, 更换网络环境。更换分流, 代理和分流组合使用, 组合使用。如果您是安卓设备, 使用全局VPN的时候, 并不需要填代理设置。

**Comment by 546649816** [comment]
感谢您的回复，问题已解决。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月21日(周日) 上午9:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [niuhuan/pikapika] 安卓9，启动1.2.2版本软件报错 (Issue #63)




 
i/o timeout , 说明链接到了服务器, 但是网络过慢, 您可以试试切换分流, 更换网络环境。更换分流, 代理和分流组合使用, 组合使用。如果您是安卓设备, 使用全局VPN的时候, 并不需要填代理设置。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
