### ISSUE TITLE
[建议] 新增取消翻页动画选项

### ISSUE THREAD

**Issue by sceraser** [niuhuan/pikapika#64]
部分图集中两张图之间只有小部分变化总体不变，官方客户端在左右翻页模式下翻动无动画，可以给人一种连续的感觉，****左右滑动有切换动画会打破这种连续感，希望加入取消翻页动画选项

**Comment by sceraser** [comment]
补充下，指的是针对差分类漫画，无动画翻页沉浸感更强

**Comment by niuhuan** [comment]
单纯的滑动一下就直接切换图片那种吗?

**Comment by sceraser** [comment]
> 单纯的滑动一下就直接切换图片那种吗?

是的，我的使用习惯是配合音量翻页，触屏翻页也可以，不管怎么翻没有动画都比有动画更好

**Comment by niuhuan** [comment]
我做好了, 你可以留下QQ或者邮箱, 还有您手机的架构(arm32 or arm64), 我打一个包给你

**Comment by sceraser** [comment]
> @sceraser 我做好了, 你可以留下QQ或者邮箱, 还有您手机的架构(arm32 or arm64), 我打一个包给你

scluyizhe@hotmail.com
arm64
感谢

**Comment by niuhuan** [comment]
在设置中开启取消翻页动画功能, 使用音量键翻页就没有动画了, 有问题可以在issue中提出

**Comment by sceraser** [comment]
> 在设置中开启取消翻页动画功能, 使用音量键翻页就没有动画了, 有问题可以在issue中提出

有两个问题

1.开启左右翻页后对分页的裁剪不对，官方客户端就可以很好的显示完整地一页

此为pika的左右分页
![Screenshot_2021-11-21-18-52-20-723_niuhuan pikapika](https://user-images.githubusercontent.com/42718757/142759143-d09c7b39-34a3-4c1b-a048-0b9c1a61fd4a.jpg)
此为官方客户端的左右分页
![Screenshot_2021-11-21-18-52-24-288_com picacomic fregata](https://user-images.githubusercontent.com/42718757/142759163-afac98b9-61eb-4820-bac2-f79b077e8a47.jpg)

2.pika翻页动画虽然取消了，但是翻页时还是有一瞬间的闪烁，官方客户端无此闪烁

此为pika的翻页效果，带闪烁
https://user-images.githubusercontent.com/42718757/142759408-d1bb29c2-aacd-4560-b437-d23d6cff77b6.mp4
此为官方客户端的翻页效果，无闪烁
https://user-images.githubusercontent.com/42718757/142759446-8c863991-deb6-4707-b209-adff66c273a1.mp4

**Comment by Z-fly** [comment]
这是哪本？

**Comment by sceraser** [comment]
> 这是哪本？作品名

emmm不管哪本pika都是错误切割的，一样的
天鹅绒之吻（上）第10集

**Comment by niuhuan** [comment]
切割错误的问题改好了, 下还没有release, 闪屏时因为缓存, 这个还在研究

**Comment by cxhttt233** [comment]
貌似相册模式翻页前不会缓存下一页以及后面页面内容，所以每次翻页后都要短暂的等待加载

**Comment by sceraser** [comment]
@niuhuan 你发给我的版本图片切割正常，但是release的版本图片切割又错误了（图2），而且新版的全屏并没有对挖孔屏/水滴屏进行优化，会被前置摄像头挡住
![IMG_20211208_225525](https://user-images.githubusercontent.com/42718757/145230099-fb61cd2c-1a43-4b16-9db4-d535768b95a8.jpg)

![Screenshot_2021-12-08-22-53-36-951_niuhuan pikapika](https://user-images.githubusercontent.com/42718757/145229773-bfdb8d91-7163-4dbb-b8da-7b3bda0843ab.jpg)

**Comment by sceraser** [comment]
而且为什么release里显示1.3版，我安装的时候是1.0？

**Comment by niuhuan** [comment]
> 而且为什么release里显示1.3版，我安装的时候是1.0？

版本号以程序和文件名为准，并没有改安卓的版本号，这样能覆盖安装到以前的版本。

**Comment by zijianjiao2017** [comment]
> 貌似相册模式翻页前不会缓存下一页以及后面页面内容，所以每次翻页后都要短暂的等待加载

pikapika iOS 版本上也有这个问题

**Comment by niuhuan** [comment]
> > 貌似相册模式翻页前不会缓存下一页以及后面页面内容，所以每次翻页后都要短暂的等待加载
> 
> pikapika iOS 版本上也有这个问题

暂时没能解决这个问题，我自己缓存了 图片，提前下载好了，但是相册组件不支持预加载，不能提前显示出来，需要给他们issue。

**Comment by zijianjiao2017** [comment]
> > > 貌似相册模式翻页前不会缓存下一页以及后面页面内容，所以每次翻页后都要短暂的等待加载
> > 
> > 
> > pikapika iOS 版本上也有这个问题
> 
> 暂时没能解决这个问题，我自己缓存了 图片，提前下载好了，但是相册组件不支持预加载，不能提前显示出来，需要给他们issue。

wwww 辛苦了

**Comment by niuhuan** [comment]
![Screenshot_20211212-221853_Chrome](https://user-images.githubusercontent.com/20847533/145716203-5d0a4395-74c3-4e21-b8f1-4bce022f0127.jpg)

@zijianjiao2017 你到底搞了什么定时任务，几小时提示一次

**Comment by sceraser** [comment]
@niuhuan 当前release版的图片切割依旧是错误的，是忘记改了吗？

**Comment by niuhuan** [comment]
> @niuhuan 当前release版的图片切割依旧是错误的，是忘记改了吗？

我记得已经改过了，可能是最近又改了UI造成的，🥶

**Comment by zijianjiao2017** [comment]
> ![Screenshot_20211212-221853_Chrome](https://user-images.githubusercontent.com/20847533/145716203-5d0a4395-74c3-4e21-b8f1-4bce022f0127.jpg)
> 
> @zijianjiao2017 你到底搞了什么定时任务，几小时提示一次

不是定时任务

是我一直在折腾（

**Comment by niuhuan** [comment]
> > ![Screenshot_20211212-221853_Chrome](https://user-images.githubusercontent.com/20847533/145716203-5d0a4395-74c3-4e21-b8f1-4bce022f0127.jpg)
> > @zijianjiao2017 你到底搞了什么定时任务，几小时提示一次
> 
> 对不起！！（不是定时任务
> 
> 是我一直在折腾（
> 
> 那我不 fork 了，直接修改 remote 然后 push 吧（

额 .... 我以为是定时任务, 你也可以搞个分支出来之类的。

**Comment by zijianjiao2017** [comment]
> > > ![Screenshot_20211212-221853_Chrome](https://user-images.githubusercontent.com/20847533/145716203-5d0a4395-74c3-4e21-b8f1-4bce022f0127.jpg)
> > > @zijianjiao2017 你到底搞了什么定时任务，几小时提示一次
> > 
> > 
> > 对不起！！（不是定时任务
> > 是我一直在折腾（
> > 那我不 fork 了，直接修改 remote 然后 push 吧（
> 
> 额 .... 我以为是定时任务, 你也可以搞个分支出来之类的, 如果有什么问题, 可以跟我问。

嗯嗯（

谢谢大佬（

**Comment by niuhuan** [comment]
> @niuhuan 你发给我的版本图片切割正常，但是release的版本图片切割又错误了（图2），而且新版的全屏并没有对挖孔屏/水滴屏进行优化，会被前置摄像头挡住 ![IMG_20211208_225525](https://user-images.githubusercontent.com/42718757/145230099-fb61cd2c-1a43-4b16-9db4-d535768b95a8.jpg)
> 
> ![Screenshot_2021-12-08-22-53-36-951_niuhuan pikapika](https://user-images.githubusercontent.com/42718757/145229773-bfdb8d91-7163-4dbb-b8da-7b3bda0843ab.jpg)

主要是为了阅读器的体验, 让安卓挖孔剩余EDGE的屏幕, 成了全屏的一部分, 可以改一下全屏UI配置。

用的是安卓的这个属性
<item name="android:windowLayoutInDisplayCutoutMode" tools:ignore="NewApi">shortEdges</item>

**Comment by niuhuan** [comment]
scrollable_positioned_list 没有动画闪烁的问题我还没有解决

**Comment by LYWXV** [comment]
啊这我进都进不去o(╥﹏╥)o
什么叫做代理地址啊哭
大佬救救啊o(╥﹏╥)o

**Comment by sceraser** [comment]
> 啊这我进都进不去o(╥﹏╥)o 什么叫做代理地址啊哭 大佬救救啊o(╥﹏╥)o

自行解决梯子问题，都上Github了还能没有梯子吗

**Comment by niuhuan** [comment]
> 啊这我进都进不去o(╥﹏╥)o 什么叫做代理地址啊哭 大佬救救啊o(╥﹏╥)o

分流挨个尝试一下，能用就不设置代理了。

手机端不用设置代理地址，直接开全局代理。

电脑端的话。
socks5://127.0.0.1:10808/
http://127.0.0.1：10807
之类的，看你的代理怎么配的。
