### ISSUE TITLE
Windows版在本子浏览界面点击全屏后会切边

### ISSUE THREAD

**Issue by kevinxluo** [niuhuan/pikapika#65]
全屏前：
![image](https://user-images.githubusercontent.com/84461294/142746410-a03d8336-f708-4c28-b59e-5666fc2b1d22.png)
![image](https://user-images.githubusercontent.com/84461294/142746441-5b5ba850-acc1-4877-b156-cfb2f98cf679.png)

全屏后：
![image](https://user-images.githubusercontent.com/84461294/142746425-111cef5a-011a-4457-bebe-3d69c0f46893.png)
![image](https://user-images.githubusercontent.com/84461294/142746452-370d4de9-d48d-4039-b5ad-f14b67da2251.png)

**Comment by niuhuan** [comment]
哈啊？🤣 了解 。

**Comment by kevinxluo** [comment]
> 哈啊？🤣 了解 。

🥰感谢老哥编译，很好用

**Comment by niuhuan** [comment]
切边只发生在横向翻页？

**Comment by kevinxluo** [comment]
> 切边只发生在横向翻页？

对，刚才试了一下上下翻页，上下翻页正常，只有左右翻页会切边

**Comment by niuhuan** [comment]
新版本已经修复

**Comment by kevinxluo** [comment]
> 新版本已经修复

牛哇，感谢老哥，ios自签包都做出来了，太照顾俺们编程苦手了👍
