### ISSUE TITLE
[问题反馈]无法记住上次阅读位置

### ISSUE THREAD

**Issue by xushet** [niuhuan/pikapika#67]
例如第一集看到一半返回再重新打开，又会回到第一集的图1

**Comment by niuhuan** [comment]
> 例如第一集看到一半返回再重新打开，又会回到第一集的图1

你点继续阅读, 不要再点第一集。

**Comment by xushet** [comment]
哦哦没注意到，深色模式按钮背景色有待优化啊

**Comment by xushet** [comment]
> 

哦哦没注意到，深色模式下按钮背景色有待优化啊
