### ISSUE TITLE
不知道该不该问，read:connection reset by peer

### ISSUE THREAD

**Issue by ShuFengMuYu** [niuhuan/pikapika#69]
一直使用分流2，最近突然遇到read:connection reset by peer的问题，请问哪位老哥有头绪吗？

**Comment by niuhuan** [comment]
> 一直使用分流2，最近突然遇到read:connection reset by peer的问题，请问哪位老哥有头绪吗？

我也遇到过，偶尔，几率很小，过一段时间才好。

出错的时候，我试过代理＋分流能用。

这个错误是了解不到服务或者服务被拒绝，比如服务没启动，或者防火墙没有打开端口。

**Comment by ShuFengMuYu** [comment]
谢谢老哥
