### ISSUE TITLE
关于x86应用

### ISSUE THREAD

**Issue by 2383741765** [niuhuan/pikapika#74]
您好，是否考虑制作windows32位软件？

**Comment by niuhuan** [comment]
flutter对windows系统的支持, 需要windows7版本以上, 并且64位架构。这款软件将不会支持32位的windows操作系统。

**Comment by 2383741765** [comment]
这样啊，明白了，谢谢

**Comment by niuhuan** [comment]
用户体验方面, 或者功能需求方面, 有没有问题?
