### ISSUE TITLE
hover build windows 报错

### ISSUE THREAD

**Issue by Misutesu** [niuhuan/pikapika#76]
您好，我在进行flutter windows打包的时候遇到问题
执行`hover build windows`命令时提示以下错误
但是`hover run`可以正常运行
```
hover: Downloading engine for platform windows-release at version bcc2b7f12cada3d1359e353c416568b4c3f6df69...
hover: Failed to download engine: Get "https://github.com/flutter-rs/engine-builds/releases/download/f-bcc2b7f12cada3d1359e353c416568b4c3f6df69/windows_x64-host_release.zip": read tcp 19
2.168.50.11:9299->20.205.243.166:443: wsarecv: An established connection was aborted by the software in your host machine.
hover: Engine builds are a bit delayed after they are published in flutter.
hover: You can either try again later or switch the flutter channel to beta, because these engines are more likely to be already built.
hover: To dig into the already built engines look at https://github.com/flutter-rs/engine-builds/releases and https://github.com/flutter-rs/engine-builds/actions
```
我在查看go-flutter-desktop的issues的时候发现了您的留言
请问下您替换engine的下载url是怎么操作的呢？
您最后的留言是替换了engine依然报错
但是我看到您在这个项目的release版本中有用hover编译好的windows release版本
请问下您是怎么解决的呢？
谢谢

**Comment by niuhuan** [comment]
看到您的错误信息, 我看到了 An established connection was aborted by the software in your host machine.

我修改了hover的源码, 下载engine的步骤, 建立连接时使用了代理。

**Comment by niuhuan** [comment]
需要注意的是, hover run 和hover build 使用引擎的下载地址并不同

**Comment by Misutesu** [comment]
您好，谢谢您的回复
从错误信息中看的话，确实是从这个链接下载错误
```
https://github.com/flutter-rs/engine-builds/releases/download/f-bcc2b7f12cada3d1359e353c416568b4c3f6df69/windows_x64-host_release.zip
```
但是我这边用浏览器直接打开这个链接显示的是`Not Found`，是能正常访问但是`bcc2b7f12cada3d1359e353c416568b4c3f6df69`这个tag下的`windows_x64-host_release.zip`是不存在的
从这个[项目](https://github.com/flutter-rs/engine-builds)的release界面看的话，很多tag中的文件都不完整，有一些缺失windows平台的文件，有一些直接就一个平台的都没有
我尝试了找一个最新的有windows平台的[tag](https://github.com/flutter-rs/engine-builds/releases/tag/f-fcbb4cb498dea49ad77a2f1f8b37853d96637973)（编译日期是2021.2.25）填入项目中`go`文件夹下`hover.yaml`
```
..................................
target: lib/main_desktop.dart
docker: false
engine-version: "fcbb4cb498dea49ad77a2f1f8b37853d96637973" # change to a engine version commit
#在这里手动填写
```
然后执行`hover build windows`
能够成功下载但是有许多关于`Dart`文件的报错，最后无法生成打包文件

然后我仔细阅读了您`pikapika`这个项目关于打包那部分的说明，尝试切换flutter版本到2.2.3，再次执行`hover build windows`，这次是从tag为`d3ea636dc5d16b56819f3266241e1f708979c233`的分支下载`windows_x64-host_release.zip`，但是依旧报错，我尝试访问这个分支和文件，分别是[`Github 404`](https://github.com/flutter-rs/engine-builds/releases/tag/f-d3ea636dc5d16b56819f3266241e1f708979c233)`和[`Not Found`](https://github.com/flutter-rs/engine-builds/releases/download/f-d3ea636dc5d16b56819f3266241e1f708979c233/windows_x64-host_release.zip)

现在我在尝试flutter版本切换到2.2.3后更改`hover.yaml`中的`engine`版本重新build，但是hover我不清楚怎么设置代理，下载速度实在是太慢了
```
G:\Develop\Flutter-Project\pikapika>hover build windows
hover: changing the engine version can lead to undesirable behavior
hover: Downloading engine for platform windows-release at version fcbb4cb498dea49ad77a2f1f8b37853d96637973...
 65 % / 100 %
```

请问一下您的`pikapika`项目昨天有发布一个release版本，其中的windows版本是如何进行打包的呢？
谢谢

**Comment by niuhuan** [comment]
因为我使用的是mac电脑, 所以我安装了vmware虚拟机, 使用ssh进行打包

mac 上的脚本
![image](https://user-images.githubusercontent.com/20847533/144347291-3c8f0151-5358-4432-9415-1e5dc1503a11.png)

windows上的脚本
![WX20211202-103434](https://user-images.githubusercontent.com/20847533/144347076-2b0b0e97-5830-4a4a-9de6-122f2247c1b9.png)

**Comment by niuhuan** [comment]
如果你的hover是新版, flutter 是旧版, 可能会有问题, 因为他们最近改了下载地址。

![image](https://user-images.githubusercontent.com/20847533/144349857-7295ad5a-303d-4e9b-a468-60e52ac2247f.png)

daf0ed1c98f1d19bcd43fa8249bf771a55159bb8

**Comment by BigCatGit** [comment]
我也遇到相同的问题，我指定的是这个版本3ad69d7be3a7231aab5525db322fc699f098315f, 但还是无法编译通过:

`hover: Generating kernel snapshot failed: exit status 254
PS D:\Github\test\GolangFlutterDesktopDemo\test_flutter> hover build windows 
hover: changing the engine version can lead to undesirable behavior
hover: Using engine from cache     
hover: Cleaning the build directory
hover: listing available plugins:  
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Bundling flutter app

 Building with sound null safety 

hover: Generating kernel snapshot
result 51ab8a42-e08a-44b1-af72-2e993db137df
Error: Error when reading '.packages': 系统找不到指定的文件。

Error: Error when reading '.packages': 系统找不到指定的文件。

Error: Couldn't resolve the package 'flutter' in 'package:flutter/material.dart'.
lib/main.dart:1:8: Error: Not found: 'package:flutter/material.dart'
import 'package:flutter/material.dart';
       ^
lib/module/hello/hello_page.dart:1:8: Error: Not found: 'package:flutter/material.dart'
import 'package:flutter/material.dart';
       ^
Error: Couldn't resolve the package 'test_flutter' in 'package:test_flutter/plugin/go/plugin.dart'.
lib/module/hello/hello_page.dart:2:8: Error: Not found: 'package:test_flutter/plugin/go/plugin.dart'
import 'package:test_flutter/plugin/go/plugin.dart';
       ^
lib/main.dart:8:21: Error: Type 'StatelessWidget' not found.
class MyApp extends StatelessWidget {
                    ^^^^^^^^^^^^^^^
lib/main.dart:13:3: Error: Type 'Widget' not found.
  Widget build(BuildContext context) {
  ^^^^^^
lib/main.dart:13:16: Error: Type 'BuildContext' not found.
  Widget build(BuildContext context) {
               ^^^^^^^^^^^^
lib/main.dart:33:26: Error: Type 'StatefulWidget' not found.
class MyHomePage extends StatefulWidget {
                         ^^^^^^^^^^^^^^
lib/main.dart:48:3: Error: Type 'State' not found.
  State<MyHomePage> createState() => _MyHomePageState();
  ^^^^^
lib/main.dart:51:32: Error: Type 'State' not found.
class _MyHomePageState extends State<MyHomePage> {
                               ^^^^^
lib/main.dart:66:3: Error: Type 'Widget' not found.
  Widget build(BuildContext context) {
  ^^^^^^
lib/main.dart:66:16: Error: Type 'BuildContext' not found.
  Widget build(BuildContext context) {
               ^^^^^^^^^^^^
lib/module/hello/hello_page.dart:4:25: Error: Type 'StatefulWidget' not found.
class HelloPage extends StatefulWidget {
                        ^^^^^^^^^^^^^^
lib/module/hello/hello_page.dart:9:31: Error: Type 'State' not found.
class _HelloPageState extends State<HelloPage> {
                              ^^^^^
lib/module/hello/hello_page.dart:11:3: Error: Type 'Widget' not found.
  Widget build(BuildContext context) {
  ^^^^^^
lib/module/hello/hello_page.dart:11:16: Error: Type 'BuildContext' not found.
  Widget build(BuildContext context) {
               ^^^^^^^^^^^^
lib/main.dart:9:9: Error: The superclass, 'StatelessWidget', has no unnamed constructor that takes no arguments.
  const MyApp({super.key});
        ^^^^^
lib/main.dart:34:9: Error: The superclass, 'StatefulWidget', has no unnamed constructor that takes no arguments.
  const MyHomePage({super.key, required this.title});
        ^^^^^^^^^^
lib/main.dart:5:3: Error: Method not found: 'runApp'.
  runApp(const MyApp());
  ^^^^^^
lib/main.dart:13:16: Error: 'BuildContext' isn't a type.
  Widget build(BuildContext context) {
               ^^^^^^^^^^^^
lib/main.dart:14:12: Error: The method 'MaterialApp' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'lib/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'MaterialApp'.
    return MaterialApp(
           ^^^^^^^^^^^
lib/main.dart:16:14: Error: The method 'ThemeData' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'lib/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'ThemeData'.
      theme: ThemeData(
             ^^^^^^^^^
lib/main.dart:26:24: Error: The getter 'Colors' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'lib/main.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Colors'.
        primarySwatch: Colors.blue,
                       ^^^^^^
lib/main.dart:55:5: Error: The method 'setState' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'lib/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'setState'.
    setState(() {
    ^^^^^^^^
lib/main.dart:66:16: Error: 'BuildContext' isn't a type.
  Widget build(BuildContext context) {
               ^^^^^^^^^^^^
lib/main.dart:98:22: Error: 'Widget' isn't a type.
          children: <Widget>[
                     ^^^^^^
lib/main.dart:99:19: Error: Couldn't find constructor 'Text'.
            const Text(
                  ^^^^
lib/main.dart:119:27: Error: Undefined name 'Icons'.
        child: const Icon(Icons.add),
                          ^^^^^
lib/main.dart:119:22: Error: Couldn't find constructor 'Icon'.
        child: const Icon(Icons.add),
                     ^^^^
lib/main.dart:73:12: Error: The method 'Scaffold' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'lib/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Scaffold'.
    return Scaffold(
           ^^^^^^^^
lib/main.dart:74:15: Error: The method 'AppBar' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'lib/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'AppBar'.
      appBar: AppBar(
              ^^^^^^
lib/main.dart:77:16: Error: The method 'Text' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'lib/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Text'.
        title: Text(widget.title),
               ^^^^
lib/main.dart:77:21: Error: The getter 'widget' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'lib/main.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'widget'.
        title: Text(widget.title),
                    ^^^^^^
lib/main.dart:79:13: Error: The method 'Center' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'lib/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Center'.
      body: Center(
            ^^^^^^
lib/main.dart:82:16: Error: The method 'Column' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'lib/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Column'.
        child: Column(
               ^^^^^^
lib/main.dart:97:30: Error: The getter 'MainAxisAlignment' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'lib/main.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'MainAxisAlignment'.
          mainAxisAlignment: MainAxisAlignment.center,
                             ^^^^^^^^^^^^^^^^^
lib/main.dart:102:13: Error: The method 'Text' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'lib/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Text'.
            Text(
            ^^^^
lib/main.dart:104:22: Error: The getter 'Theme' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'lib/main.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Theme'.
              style: Theme.of(context).textTheme.headlineMedium,
                     ^^^^^
lib/main.dart:109:29: Error: The method 'FloatingActionButton' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'lib/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'FloatingActionButton'.
      floatingActionButton: FloatingActionButton(
                            ^^^^^^^^^^^^^^^^^^^^
lib/main.dart:112:17: Error: The getter 'Navigator' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'lib/main.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Navigator'.
          await Navigator.of(context).push(
                ^^^^^^^^^
lib/main.dart:113:13: Error: The method 'MaterialPageRoute' isn't defined for the class '_MyHomePageState'.
 - '_MyHomePageState' is from 'lib/main.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'MaterialPageRoute'.
            MaterialPageRoute(builder: (_) {
            ^^^^^^^^^^^^^^^^^
lib/module/hello/hello_page.dart:11:16: Error: 'BuildContext' isn't a type.
  Widget build(BuildContext context) {
               ^^^^^^^^^^^^
lib/module/hello/hello_page.dart:14:22: Error: Couldn't find constructor 'Text'.
        title: const Text('Hello'),
                     ^^^^
lib/module/hello/hello_page.dart:18:20: Error: 'Widget' isn't a type.
        children: <Widget>[
                   ^^^^^^
lib/module/hello/hello_page.dart:23:30: Error: Couldn't find constructor 'Text'.
                return const Text('Hello插件执行出错');
                             ^^^^
lib/module/hello/hello_page.dart:12:12: Error: The method 'Scaffold' isn't defined for the class '_HelloPageState'.
 - '_HelloPageState' is from 'lib/module/hello/hello_page.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Scaffold'.
    return Scaffold(
           ^^^^^^^^
lib/module/hello/hello_page.dart:13:15: Error: The method 'AppBar' isn't defined for the class '_HelloPageState'.
 - '_HelloPageState' is from 'lib/module/hello/hello_page.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'AppBar'.
      appBar: AppBar(
              ^^^^^^
lib/module/hello/hello_page.dart:16:13: Error: The method 'Center' isn't defined for the class '_HelloPageState'.
 - '_HelloPageState' is from 'lib/module/hello/hello_page.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Center'.
      body: Center(
            ^^^^^^
lib/module/hello/hello_page.dart:17:18: Error: The method 'Column' isn't defined for the class '_HelloPageState'.
 - '_HelloPageState' is from 'lib/module/hello/hello_page.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Column'.
          child: Column(
                 ^^^^^^
lib/module/hello/hello_page.dart:19:11: Error: The method 'FutureBuilder' isn't defined for the class '_HelloPageState'.
 - '_HelloPageState' is from 'lib/module/hello/hello_page.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'FutureBuilder'.
          FutureBuilder<String?>(
          ^^^^^^^^^^^^^
lib/module/hello/hello_page.dart:20:21: Error: The getter 'HelloPlugin' isn't defined for the class '_HelloPageState'.
 - '_HelloPageState' is from 'lib/module/hello/hello_page.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'HelloPlugin'.
            future: HelloPlugin.hello(),
                    ^^^^^^^^^^^
lib/module/hello/hello_page.dart:25:22: Error: The method 'Text' isn't defined for the class '_HelloPageState'.
 - '_HelloPageState' is from 'lib/module/hello/hello_page.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Text'.
              return Text(snapshot.data!);
                     ^^^^
51ab8a42-e08a-44b1-af72-2e993db137df
+file:///D:/Github/test/GolangFlutterDesktopDemo/test_flutter/lib/main_desktop.dart
+file:///D:/Github/test/GolangFlutterDesktopDemo/test_flutter/lib/main.dart
+file:///D:/Github/test/GolangFlutterDesktopDemo/test_flutter/lib/module/hello/hello_page.dart
51ab8a42-e08a-44b1-af72-2e993db137df D:\Github\test\GolangFlutterDesktopDemo\test_flutter\go\build\outputs\windows-release\kernel_snapshot.dill 55
hover: Generating kernel snapshot failed: exit status 254`

**Comment by niuhuan** [comment]
2.10.3
engine-version: "bd539267b42051b0da3d16ffa8f48949dce8aa8f"
可编译通过

**Comment by BigCatGit** [comment]
非常感谢，我试了这个版本，还是出现错误, 有可能这个版本与我本地的flutter版本不兼容
lib/main_desktop.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.16.  
import 'main.dart' as original_main;

**Comment by niuhuan** [comment]
> 非常感谢，我试了这个版本，还是出现错误, 有可能这个版本与我本地的flutter版本不兼容 lib/main_desktop.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.16. import 'main.dart' as original_main;

这是依赖库版本太高。

去pub.dev ，在依赖库version里面查。
参考Pikapika的工作流里面的sed。

**Comment by BigCatGit** [comment]
刚刚接触flutter, 有点不太明白您说的解决办法应该怎么操作, 可以讲白一吗，非常感谢

**Comment by niuhuan** [comment]
> 刚刚接触flutter, 有点不太明白您说的解决办法应该怎么操作, 可以讲白一吗，非常感谢

pubspec.yaml 中

dependencies 节点中的内容，版本需要降低到flutter2支持

**Comment by BigCatGit** [comment]
我的配置如下:
hover.yaml

target: lib/main_desktop.dart
docker: false
engine-version: "bd539267b42051b0da3d16ffa8f48949dce8aa8f" # change to a engine version commit

pubspec.ymal 如下

version: 1.0.0+1

environment:
    # sdk: ">=2.19.4 <3.0.0"
    sdk: "2.10.3"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter

这样配置正确吗

**Comment by niuhuan** [comment]
> 我的配置如下: hover.yaml
> 
> target: lib/main_desktop.dart docker: false engine-version: "bd539267b42051b0da3d16ffa8f48949dce8aa8f" # change to a engine version commit
> 
> pubspec.ymal 如下
> 
> version: 1.0.0+1
> 
> environment: # sdk: ">=2.19.4 <3.0.0" sdk: "2.10.3"
> 
> dependencies: flutter: sdk: flutter cupertino_icons: ^1.0.2
> 
> dev_dependencies: flutter_test: sdk: flutter
> 
> 这样配置正确吗

我并不是说修改environment.sdk，而是在你的flutterSdk 里 git checkout 2.10.3

**Comment by BigCatGit** [comment]
这个明白了，好的好的，太感谢了
