### ISSUE TITLE
Target 31+ requires an explicit value

### ISSUE THREAD

**Issue by SukiEva** [niuhuan/pikapika#77]
Flutter 不指定编译不会报错嘛😂

**日志**
```
INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: 
Failed parse during installPackageLI: /data/app/vmdl1556595146.tmp/base.apk (at Binary XML file line #33):niuhuan.pikapika.MainActivity: 
Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present
```
~另外apk version code 一直都是 1.0.0~

**Comment by niuhuan** [comment]
您是在安卓12设备中无法安装吗？我是因为升级了flutter不得已才升级了SDK，否则没办法编译通过。

**Comment by SukiEva** [comment]
> 您是在安卓12设备中无法安装吗？我是因为升级了flutter不得已才升级了SDK，否则没办法编译通过。

是的，不过我之前 Android Studio 指向 Target 32 的时候，编译会提示需要定义 `android:exported` ，可能安卓12以下也安装不上😶

**Comment by niuhuan** [comment]
我刚才在安卓11,和安卓7都试了没有问题。

compileSdkVersion 和 targetSdkVersion 都改成了31, 我现在把targetSdkVersion改回去再编译一下, 然后您再试试。

**Comment by niuhuan** [comment]
我将把targetSdkVersion改回30, 并已经更新了**pikapika_v1.3.1_arm64.apk**和**pikapika_v1.3.1.apk**, 您需要重新下载并试一下。恳请您安装后进行反馈。

**Comment by SukiEva** [comment]
> 我将把targetSdkVersion改回30, 并已经更新了**pikapika_v1.3.1_arm64.apk**和**pikapika_v1.3.1.apk**, 您需要重新下载并试一下。恳请您安装后进行反馈。

可以了，确实是安卓12的问题

**Comment by niuhuan** [comment]
🙏  感谢
