### ISSUE TITLE
Release 中提供的 IPA 包过大

### ISSUE THREAD

**Issue by zijianjiao2017** [niuhuan/pikapika#81]
如图，iOS 的包远大于其他平台的

<img width=800 src="https://user-images.githubusercontent.com/61231083/146054281-8e0f767e-bb8a-44a8-9d58-65f4ece39360.png"/>

> [也许是因为没有签名，而且这好像是 xcodebuild 的一个预期行为](https://stackoverflow.com/questions/56058452/why-unsigned-xcarchive-is-larger-than-signed)
>
> 我在完整的 xcodebuild 输出中发现了[这个](https://github.com/zijianjiao2017/pikapika/runs/4523494207?check_suite_focus=true#step:13:20185)

于是我尝试了 [使用](https://github.com/zijianjiao2017/pikapika/blob/main/.github/workflows/release.yaml#L106) [脚本](https://github.com/zijianjiao2017/pikapika/blob/main/script/strip_copy.py) 来手动去除生成的 `Runner.app` 中一些二进制中的 BitCode, 一些通用二进制中未使用的架构（仅保留 arm64 的）, 以及其中的 debug 和 local 符号

#### 成效显著：

<img width=800 src="https://user-images.githubusercontent.com/61231083/146055460-1cb27e69-6951-4016-a362-e3576e58bbf0.png"/>
使用这个脚本瘦身过的安装包可以在我的设备（iPhone 7 + iOS 12.4.1）上使用 AltStore 正常安装 & 使用

**Comment by zijianjiao2017** [comment]
所以这个可以作为参考嘛？（

**Comment by niuhuan** [comment]
我觉得不错。

刚用搜索引擎查了一下，2018年后（IphoneXS）是ARM64E架构。如果像安卓一样向下兼容是最好，不知道Arm64是否兼容armv7，Arm64e是否兼容arm64

**Comment by zijianjiao2017** [comment]
> 我觉得不错。
> 
> 刚用搜索引擎查了一下，2018年后（IphoneXS）是ARM64E架构。如果像安卓一样向下兼容是最好，不知道Arm64是否兼容armv7，Arm64e是否兼容arm64

兼容，但是 iOS 11 开始抛弃 32 位了

**Comment by zijianjiao2017** [comment]
https://developer.apple.com/library/archive/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/DeviceCompatibilityMatrix/DeviceCompatibilityMatrix.html

**Comment by niuhuan** [comment]
我获取了几个Runner.app内文件的信息

```shell
➜  Payload/Runner.app/Runner 
           Non-fat file: Payload/Runner.app/Runner is architecture: arm64
➜  Payload/Runner.app/Frameworks/App.framework/App 
           Architectures in the fat file: Payload/Runner.app/Frameworks/App.framework/App are: arm64 
➜  Payload/Runner.app/Frameworks/libswiftCore.dylib 
           Architectures in the fat file: Payload/Runner.app/Frameworks/libswiftCore.dylib are: armv7 armv7s arm64 arm64e 
➜  Payload/Runner.app/Frameworks/url_launcher_ios.framework/url_launcher_ios
           Architectures in the fat file: Payload/Runner.app/Frameworks/url_launcher_ios.framework/url_launcher_ios are: arm64 
```
![QQ20211215-094602](https://user-images.githubusercontent.com/20847533/146107789-ab506954-5375-464c-9f80-c09a40a1725a.png)

只有和swift相关的有库是所有架构的, 其余的都是arm64架构, 也可能是xcode搞的。

**Comment by niuhuan** [comment]
我又上传了一个ipa, 我把dylib和可执行文件都精简了, 手头没有iphone不确定是不是能用

**Comment by zijianjiao2017** [comment]
> 我获取了几个Runner.app内文件的信息
> 
> ```shell
> ➜  Payload/Runner.app/Runner 
>            Non-fat file: Payload/Runner.app/Runner is architecture: arm64
> ➜  Payload/Runner.app/Frameworks/App.framework/App 
>            Architectures in the fat file: Payload/Runner.app/Frameworks/App.framework/App are: arm64 
> ➜  Payload/Runner.app/Frameworks/libswiftCore.dylib 
>            Architectures in the fat file: Payload/Runner.app/Frameworks/libswiftCore.dylib are: armv7 armv7s arm64 arm64e 
> ➜  Payload/Runner.app/Frameworks/url_launcher_ios.framework/url_launcher_ios
>            Architectures in the fat file: Payload/Runner.app/Frameworks/url_launcher_ios.framework/url_launcher_ios are: arm64 
> ```
> 
> ![QQ20211215-094602](https://user-images.githubusercontent.com/20847533/146107789-ab506954-5375-464c-9f80-c09a40a1725a.png)
> 
> 只有和swift相关的有库是所有架构的, 其余的都是arm64架构, 也可能是xcode搞的。

[从 go 1.15 开始](https://go.dev/doc/go1.15#darwin) 

[gomobile 就不支持 darwin/arm 了](https://github.com/golang/go/issues/41074#issuecomment-682448023) (`gomobile bind -target=ios` 现在默认包含 arm64 和 amd64)，swift 的这个应该因为是 Xcode 没有自动清理未使用的架构

**Comment by zijianjiao2017** [comment]
> 我又上传了一个ipa, 我把dylib和可执行文件都精简了, 手头没有iphone不确定是不是能用

等一下我去试试（

**Comment by niuhuan** [comment]
那我试试这样
```
gomobile bind -target=ios/arm64 -o lib/Mobile.xcframework ./
```

**Comment by zijianjiao2017** [comment]
> 那我试试这样
> 
> ```
> gomobile bind -target=ios/arm64 -o lib/Mobile.xcframework ./
> ```

试了，没有用（

**Comment by zijianjiao2017** [comment]
这些文件会不会是在 SDK 里面预编译好的，然后 xcodebuild 复制过来的？

**Comment by zijianjiao2017** [comment]
也许 xcodebuild 只有在打包 xcarchive 或者 IPA 的时候才会清理未使用的架构？

**Comment by zijianjiao2017** [comment]
> 我又上传了一个ipa, 我把dylib和可执行文件都精简了, 手头没有iphone不确定是不是能用

在我的 iPhone 7 (arm64, iOS 12.4.1) 上用 AltStore 安装之后可以用

**Comment by zijianjiao2017** [comment]
但是这个 IPA 好像还是显示最低需要 iOS 9（？

**Comment by niuhuan** [comment]
我使用1.3.2直接精简的

**Comment by zijianjiao2017** [comment]
oo
