### ISSUE TITLE
[BUG] 相册模式很糊

### ISSUE THREAD

**Issue by TenmaSennpai** [niuhuan/pikapika#83]
相册模式很糊，但是webtoon模式又不能整页翻页
图片：[img](https://imgur.com/a/20cyoXZ)

**Comment by niuhuan** [comment]
🤔   webtoon 模式你可以用那个将屏幕分成三个区域的控制模式, 一页一页的翻看。 

相册模式很糊 🤔 🤔 🤔  会不会和图片大小有关。

**Comment by niuhuan** [comment]
不知道你喜不喜欢那种  点击屏幕一下可以翻页, 双击屏幕放大 的操作

**Comment by zijianjiao2017** [comment]
@niuhuan 你用的是相册组件自带的缩放还是自己实现的（

**Comment by zijianjiao2017** [comment]
会不会是平滑缩放没有优化好？（

**Comment by niuhuan** [comment]
> @niuhuan 你用的是相册组件自带的缩放还是自己实现的（

photo_view 啊, 我直接给的imageProivder, 缩放什么的都是他自己实现的

**Comment by zijianjiao2017** [comment]
> > @niuhuan 你用的是相册组件自带的缩放还是自己实现的（
> 
> photo_view 啊, 我直接给的imageProivder, 缩放什么的都是他自己实现的

ok 我折腾一下看看（

**Comment by zijianjiao2017** [comment]
修好了（
等一下发 pr（

**Comment by niuhuan** [comment]
![1111](https://user-images.githubusercontent.com/20847533/146213723-9ecc84fb-4250-49d1-8685-891afd7f7a65.png)

这个颜色不知道怎么调,  找了好久
