### ISSUE TITLE
windows端下载导出时有问题

### ISSUE THREAD

**Issue by Minori-ty** [niuhuan/pikapika#90]

**Comment by niuhuan** [comment]
你可以设置一下浏览器根路径，比如设置成 D:/

**Comment by Minori-ty** [comment]
> 你可以设置一下浏览器根路径，比如设置成 D:/

好的，成功了，不过导出时还是在软件的目录里。

**Comment by lpq147258** [comment]
希望以后作者开个禁漫天堂的新坑，这个资源更多

**Comment by niuhuan** [comment]
> 希望以后作者开个禁漫天堂的新坑，这个资源更多

有没有项目做参考？

**Comment by Minori-ty** [comment]
> > 希望以后作者开个禁漫天堂的新坑，这个资源更多
> 
> 有没有项目做参考？

这是我搜到的一个用react native写的，可以看一下他的api
https://github.com/justagoodman/JMComic

**Comment by niuhuan** [comment]
导出的问题改好放在最新的release里了

**Comment by niuhuan** [comment]
这个项目并不值得参考，一些api只有一页，更多api失效了，盐值算法还可以用，不知道原版app叫什么，或许可以对原版app抓包。

**Comment by niuhuan** [comment]
@zhongfly 

根据他给的项目, 已经可以成功请求video, latest 几个接口, 使用app协议,如果使用web页面去匹配真的是太low了。

jm使用reactNative打包, webpack打包后代码十分混乱, 没有找到解包工具。

httpCanary 无法抓包。大佬有什么办法抓到参数和接口吗?

**Comment by zhongfly** [comment]
> @zhongfly
> 
> 根据他给的项目, 已经可以成功请求video, latest 几个接口, 使用app协议,如果使用web页面去匹配真的是太low了。
> 
> jm使用reactNative打包, webpack打包后代码十分混乱, 没有找到解包工具。
> 
> httpCanary 无法抓包。大佬有什么办法抓到参数和接口吗?

我没抓过这个，不清楚情况。但可以尝试用电脑上的安卓模拟器，导入抓包软件的证书(模拟器一般有root，可以添加为系统证书)，然后模拟器里设置代理转发到电脑上的fidder或者postman。
如果证书还是有问题，可以折腾xposed，有插件可以避免证书验证或固定。(TrustMeAlready)
另外，我常用的漫画软件tachiyomi，已经有这个源了。https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/src/zh/jinmantiantang

**Comment by Minori-ty** [comment]
> > @zhongfly
> > 
> > 根据他给的项目, 已经可以成功请求video, latest 几个接口, 使用app协议,如果使用web页面去匹配真的是太low了。
> > 
> > jm使用reactNative打包, webpack打包后代码十分混乱, 没有找到解包工具。
> > 
> > httpCanary 无法抓包。大佬有什么办法抓到参数和接口吗?
> 
> 我没抓过这个，不清楚情况。但可以尝试用电脑上的安卓模拟器，导入抓包软件的证书(模拟器一般有root，可以添加为系统证书)，然后模拟器里设置代理转发到电脑上的fidder或者postman。
> 如果证书还是有问题，可以折腾xposed，有插件可以避免证书验证或固定。(TrustMeAlready)
> 另外，我常用的漫画软件tachiyomi，已经有这个源了。https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/src/zh/jinmantiantang
> 
> edit：刚试了，能抓到啊。我只是添加了httpcanary的证书为系统证书。只不过看json内容是有加密，可能需要反编译apk，去找解密方法

大家都热爱这个，我觉得可以成立个抓包组织，专门抓包漫画app的api

**Comment by niuhuan** [comment]
json解密我已经做好了,但是我的设备没有root

**Comment by zhongfly** [comment]
> json解密我已经做好了,但是我的设备没有root

…模拟器啊，都有root的

**Comment by niuhuan** [comment]
API部分准备的差不多了, 官方APP界面真丑, 不知道怎么搞他才好。

**Comment by niuhuan** [comment]
已经有个大概了

![QQ20220101-221628](https://user-images.githubusercontent.com/20847533/147854417-038bfdb1-ffe6-4dec-9a7e-024542c14978.png)

![QQ20220101-234752](https://user-images.githubusercontent.com/20847533/147854420-af14bf8c-508b-439e-b151-0cd36fc69d51.png)

**Comment by niuhuan** [comment]
https://github.com/niuhuan/jasmine

**Comment by Minori-ty** [comment]
> https://github.com/niuhuan/jasmine

大哥，有api文档吗

**Comment by niuhuan** [comment]
> > https://github.com/niuhuan/jasmine
> 
> 大哥，有api文档吗

参考你给的那个仓库解码，先用js把他算的盐值打印出来，盐值是不变的，然后再抓包官方app。

**Comment by Minori-ty** [comment]
> > > https://github.com/niuhuan/jasmine
> > 
> > 
> > 大哥，有api文档吗
> 
> 参考你给的那个仓库解码，先用js把他算的盐值打印出来，盐值是不变的，然后再抓包官方app。

我不会抓包手机app

**Comment by niuhuan** [comment]
就是用 http canary 看他怎么请求的
