### ISSUE TITLE
禁漫天堂已开坑, 资源丰富, 请多多点赞支持

### ISSUE THREAD

**Issue by niuhuan** [niuhuan/pikapika#91]
https://github.com/niuhuan/jasmine

**Comment by yzx23333** [comment]
感谢作者的这个作品，让阅读体验大幅上升。希望后续如出现问题还能有时间维护～还有一点，希望能改进出双指放大模式listview下的进度条或跳页功能，如果大佬没时间弄也没事😘

**Comment by niuhuan** [comment]
> 感谢作者的这个作品，让阅读体验大幅上升。希望后续如出现问题还能有时间维护～还有一点，希望能改进出双指放大模式listview下的进度条或跳页功能，如果大佬没时间弄也没事😘

@yzx23333 

😂 也不全是因为没时间，还需要学习很久才能做那个。

因为图片的高度是未知的，滚动渲染的时候下载完图片才知道多高这个时候滚动条长度会变化，无法正确监听。

这个时候用了个按照控件滚动的组件，这个组件还不能配合双指放大。

原生能双指放大的组建不能按照组件个数滚动。

😂就是你看到的这个样子了。

**Comment by yzx23333** [comment]
没想到作者大大回复这么快。
如果高度位置，那能否预留高度后载入图片后再调整高度呢，这样应该能确定对应图片和位置了

还有两个小建议：阅读页面背景不要用纯黑，A屏晚上看已经瞎掉了😂像#FF303030这种颜色就要好多了；还希望替换软件内所有的那个大红色载入错误的X，在一堆图片中出现实在是很突兀😂换成浅灰色顺时针图标这种也行的

**Comment by niuhuan** [comment]
预留高度了但是，还是有高度差

**Comment by niuhuan** [comment]
我最理想的是， 某卡，某pixi，某jm，某n做成一个客户端。
