### ISSUE TITLE
请问IOS要求的最低版本是多少

### ISSUE THREAD

**Issue by DarthMikuH** [niuhuan/pikapika#94]

**Comment by niuhuan** [comment]
11

**Comment by 4zuk1** [comment]
9 不行吗？（假如有 64 位的话

**Comment by 4zuk1** [comment]
虽然过编译了，但是我没有 iOS 9 设备，不保证能用：[here](https://github.com/4zuk1/pikapika/releases/download/v1.3.7/pikapika_v1.3.7_411548a_ios_arm64_unsigned.ipa)

**Comment by niuhuan** [comment]
🙅‍♂️  ipa至少是11

- 如果想使用 Thread{}.start() 至少是10 (可以改代码兼容)
- 如果想不签名编译成ipa至少是11, 我不知道为什

**Comment by 4zuk1** [comment]
> no_good_man ipa至少是11
> 
> * 如果想使用 Thread{}.start() 至少是10 (可以改代码兼容)
> * 如果想不签名编译成ipa至少是11, 我不知道为什

话说如果没有签名怎么在 9 上安装, AltStore 好像不能运行在那么老的版本吧...

但如果有越狱直接 ldid 签就行了

**Comment by aTyrion** [comment]
最低要求是11，我的是12.1.3一打开就闪退，是版本问题吗？

**Comment by niuhuan** [comment]
@4zuk1  我的手机装不上ipa唉 , ios 12.4 的系统, 很老的ipa可以

**Comment by 4zuk1** [comment]
> @4zuk1 我的手机装不上ipa唉 , ios 12.4 的系统, 很老的ipa可以

xdd 我也没测试过

你试试 altstore?

**Comment by niuhuan** [comment]
脚本有点问题，没有精简，别的都正常。我altstore闪退。我只想知道pikapika和jasmine的ipa还能用吗？

**Comment by niuhuan** [comment]
@aTyrion 你是怎么装上的

**Comment by 4zuk1** [comment]
sideloadly?

**Comment by niuhuan** [comment]
> sideloadly?

有没有手机端的工具

**Comment by huangfengye** [comment]
13PM 15.3系统, altstore签名，正常可用。
