### ISSUE TITLE
是否可以继续瘦身 APK?

### ISSUE THREAD

**Issue by ghost** [niuhuan/pikapika#96]
我做了个脚本: [here](https://github.com/4zuk1/pikapika/blob/dev/.github/workflows/android-arm64.yaml#L175)

## 效果
| Before |
| ---- |
| ![image](https://user-images.githubusercontent.com/96861074/153421911-480059f8-6b0f-4fa4-9ebd-330359b46d33.png) |

| After |
| ---- |
| ![image](https://user-images.githubusercontent.com/96861074/153421768-7313b013-3b7b-4891-b3df-1aafd9b58486.png) |

**Comment by 4zuk1** [comment]
@niuhuan 我加上 `target-platform` 选项之后重新编译，大小似乎和前面一样（

<img src="https://user-images.githubusercontent.com/96861074/153433361-c6d3daf7-b24e-4419-acd6-22e12d45a2e2.png" width="1024">

**Comment by niuhuan** [comment]
--target-platform 只是直接打目标平台的包

**Comment by 4zuk1** [comment]
> 应该是因为用了 `zipalign` 重新压缩，或者是一些多余的符号被去除了

我加了那个 `-z: recompress using Zopfli` 选项

**Comment by 4zuk1** [comment]
我发现在 `flutter build apk -h` 里面有这个选项的说明:

````text
--target-platform               The target platform for which the app is
                                    compiled.
                                    [android-arm (default), android-arm64
                                    (default), android-x86, android-x64
                                    (default)]
````

**Comment by niuhuan** [comment]
我试了一下x64可以, x86不可以, 这就很奇怪, x86的模拟器可以用, 却不能release.

```shell
# flutter build apk --target-platform android-x86
Cannot build release mode for x86 ABI.
For more information see https://flutter.dev/docs/deployment/android#what-are-the-supported-target-architectures 
```
