### ISSUE TITLE
ARM Native build for macOS

### ISSUE THREAD

**Issue by ipfans** [niuhuan/pikapika#97]
性能原因考虑，M1系列需要一个原生版本~

**Comment by niuhuan** [comment]
1

**Comment by niuhuan** [comment]
我没有m1的设备, 这很成问题, 我只有具体思路。

---

1. 编译flutter引擎, 使得hover支持m1。 (pikapika代码不需要动, 需要修改hover代码, 翻车风险较大)
2. 通过ffi使得m1支持。 (需要修改pikapika代码, 翻车风险一般)
