### ISSUE TITLE
希望开发者能加个平板双页模式

### ISSUE THREAD

**Issue by ggtony233** [niuhuan/pikapika#98]
平板横着用的时候，没有双页，一整个屏幕看不到完整的一页，难顶
![](https://s3.bmp.ovh/imgs/2022/02/b2752ed54b825f67.jpg)

**Comment by ggtony233** [comment]
根本没有从左到右这个选项，我想要的双页是一个屏幕里面能展示两页且有左边第一页右边第二页或者左边第二页右边第一页这种，因为当大屏设备在横屏的时候，要么是看不完一张图片，要不是屏幕两边有很大的黑边，而且这个软件根本没有横屏的，从右到左，只有从上到下的webtoon和连续。发自我的华为平板-------- 原始邮件 --------发件人： niuhuan ***@***.***>日期： 2022年2月18日周五 晚上10:22收件人： niuhuan/pikapika ***@***.***>抄送： ggtony233 ***@***.***>, Author ***@***.***>主    题： Re: [niuhuan/pikapika] 希望开发者能加个平板双页模式 (Issue #98)

你先试试将翻页方向变成从左到右, 体验一下。

然后说一下期待的大致操作方式或体验。

**Comment by ggtony233** [comment]
就像这样![](https://s3.bmp.ovh/imgs/2022/02/aebdbc1c84f9edeb.jpg)

**Comment by ggtony233** [comment]
就像这么搞
![Screenshot_20220219_151309_com kiwibrowser browser](https://user-images.githubusercontent.com/72987782/154791064-c996b1ce-d722-4df3-b11b-5fa489258dbe.jpg)

**Comment by niuhuan** [comment]
![11](https://user-images.githubusercontent.com/20847533/154791072-49095655-5dd7-48a3-b4b3-f77ecf1bf102.png)

![22](https://user-images.githubusercontent.com/20847533/154791080-b31ba0b9-a787-4d6f-981b-85a23d45a183.png)

**Comment by niuhuan** [comment]
就像这样, 可以横向滚屏

**Comment by ggtony233** [comment]
啊这，那没事了
