### ISSUE TITLE
最低要求是11，我的是12.1.3一打开就闪退，是版本问题吗？刚刚下载的

### ISSUE THREAD

**Issue by aTyrion** [niuhuan/pikapika#99]
最低要求是11，我的是12.1.3一打开就闪退，是版本问题吗？

_Originally posted by @aTyrion in https://github.com/niuhuan/pikapika/issues/94#issuecomment-1046275304_

**Comment by niuhuan** [comment]
？？？？？

**Comment by niuhuan** [comment]
我12.4的iphone8没什么问题

**Comment by aTyrion** [comment]
那就不清楚了，也没去试试旧版本，我下了隔壁简约的那个正常使用
